In [1]:
import pandas as pd
from operator import itemgetter
import re
import pymongo

In [18]:
def fix_names(x):
    if (isinstance(x,str)):
        x.replace(r'\n', "")
        y = x.split(r' (')
        return y[0]

def remove_dashes(x):
    pattern1 = '\u2013'
    pattern2 = '-'
    pattern3 = '.*\u20ac.*'
    
    if (isinstance(x,str)):
        if (re.match(pattern1,x) or re.match(pattern2,x) or re.match(pattern3,x)):
            y = 0
            return y
        else:
            return int(x)
    else:
        return x

us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)
db = client.etl_project_db
db.vehicle_records.drop()
db.pollution_records.drop()

In [19]:
for sheet in range(2, 8):
    # collect data for each year 2012 - 2017
    
    pYear = 2010 + sheet
    year = str(pYear)
    url = 'https://www.fhwa.dot.gov/policyinformation/statistics/{}/mv1.cfm'.format(year)
    table = pd.read_html(url)
    
    # fix column names
    COLUMNS = ['state','private_cars','public_cars','total_cars','private_buses','public_buses','total_buses','private_trucks','public_trucks','total_trucks','private_motorcycles','public_motorcycles','total_motorcycles','all_private','all_public','total']
    table[0].columns= COLUMNS
    
    # fix state names and replace special charcters within data with zero's
    chk_df = table[0].copy()
    chk2_series = chk_df['state'].apply(fix_names)
    chk_df['state'] = chk2_series
    chk_df[chk_df.columns[1:]] = chk_df[chk_df.columns[1:]].applymap(remove_dashes)
    
    # drop 'dist of col' and 'total' rows, reset index

    chk_df.drop(chk_df[chk_df['state'] == 'Dist. of Col.'].index,inplace=True)
    chk_df.drop(chk_df[chk_df['state'] == 'Total'].index,inplace=True)
    chk_df.reset_index(drop=True,inplace=True)

    # add state abbr. and year columns

    sa = []
    year_col = []
    for n,v in chk_df["state"].iteritems():
        sa.append(us_state_abbrev[v])
        year_col.append(year)
    
    chk_df["state_abbr"] = pd.Series(sa)
    chk_df['year'] = pd.Series(year_col)
    COLUMNS.append('state_abbr')
    COLUMNS.append('year')
    
    # build list of records to input into db
    
    db_input = []
    for index, row in chk_df.iterrows():
        state_record = {}
        for i in COLUMNS:
            state_record[i] = row[i]
        db_input.append(state_record)
        
    # input records into db
    
    db.vehicle_records.insert_many(db_input)
    print(db_input)

[{'state': 'Alabama', 'private_cars': 2024677, 'public_cars': 17812, 'total_cars': 2042489, 'private_buses': 1037, 'public_buses': 4662, 'total_buses': 5699, 'private_trucks': 2641310, 'public_trucks': 22669, 'total_trucks': 2663979, 'private_motorcycles': 132432, 'public_motorcycles': 33, 'total_motorcycles': 132465, 'all_private': 4799456, 'all_public': 45176, 'total': 4844632, 'state_abbr': 'AL', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d4')}, {'state': 'Alaska', 'private_cars': 189301, 'public_cars': 3850, 'total_cars': 193151, 'private_buses': 2114, 'public_buses': 1373, 'total_buses': 3487, 'private_trucks': 535789, 'public_trucks': 10878, 'total_trucks': 546667, 'private_motorcycles': 31933, 'public_motorcycles': 7, 'total_motorcycles': 31940, 'all_private': 759137, 'all_public': 16108, 'total': 775245, 'state_abbr': 'AK', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d5')}, {'state': 'Arizona', 'private_cars': 2101007, 'public_cars': 23034, 'total_cars': 2124041, 'private_buses': 7214, 'public_buses': 13636, 'total_buses': 20850, 'private_trucks': 2837688, 'public_trucks': 31680, 'total_trucks': 2869368, 'private_motorcycles': 148752, 'public_motorcycles': 4, 'total_motorcycles': 148756, 'all_private': 5094661, 'all_public': 68353, 'total': 5163015, 'state_abbr': 'AZ', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d6')}, {'state': 'Arkansas', 'private_cars': 840272, 'public_cars': 41000, 'total_cars': 881272, 'private_buses': 1313, 'public_buses': 9222, 'total_buses': 10535, 'private_trucks': 1499788, 'public_trucks': 12235, 'total_trucks': 1512023, 'private_motorcycles': 76085, 'public_motorcycles': 0, 'total_motorcycles': 76085, 'all_private': 2417458, 'all_public': 62457, 'total': 2479915, 'state_abbr': 'AR', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d7')}, {'state': 'California', 'private_cars': 12999038, 'public_cars': 224784, 'total_cars': 13223822, 'private_buses': 54498, 'public_buses': 38807, 'total_buses': 93305, 'private_trucks': 13276984, 'public_trucks': 320518, 'total_trucks': 13597502, 'private_motorcycles': 772344, 'public_motorcycles': 15177, 'total_motorcycles': 787521, 'all_private': 27102864, 'all_public': 599286, 'total': 27702150, 'state_abbr': 'CA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d8')}, {'state': 'Colorado', 'private_cars': 1728413, 'public_cars': 17775, 'total_cars': 1746188, 'private_buses': 7220, 'public_buses': 4539, 'total_buses': 11759, 'private_trucks': 2592033, 'public_trucks': 28035, 'total_trucks': 2620068, 'private_motorcycles': 183819, 'public_motorcycles': 62, 'total_motorcycles': 183881, 'all_private': 4511485, 'all_public': 50411, 'total': 4561896, 'state_abbr': 'CO', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9d9')}, {'state': 'Connecticut', 'private_cars': 1370468, 'public_cars': 16611, 'total_cars': 1387079, 'private_buses': 3503, 'public_buses': 8582, 'total_buses': 12085, 'private_trucks': 1207938, 'public_trucks': 16025, 'total_trucks': 1223963, 'private_motorcycles': 83332, 'public_motorcycles': 0, 'total_motorcycles': 83332, 'all_private': 2665241, 'all_public': 41218, 'total': 2706459, 'state_abbr': 'CT', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9da')}, {'state': 'Delaware', 'private_cars': 438074, 'public_cars': 4039, 'total_cars': 442113, 'private_buses': 2610, 'public_buses': 1855, 'total_buses': 4465, 'private_trucks': 461636, 'public_trucks': 4698, 'total_trucks': 466334, 'private_motorcycles': 30730, 'public_motorcycles': 0, 'total_motorcycles': 30730, 'all_private': 933050, 'all_public': 10592, 'total': 943642, 'state_abbr': 'DE', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9db')}, {'state': 'Florida', 'private_cars': 7471652, 'public_cars': 64204, 'total_cars': 7535856, 'private_buses': 13556, 'public_buses': 17678, 'total_buses': 31234, 'private_trucks': 7411442, 'public_trucks': 68302, 'total_trucks': 7479744, 'private_motorcycles': 619079, 'public_motorcycles': 73, 'total_motorcycles': 619152, 'all_private': 15515729, 'all_public': 150257, 'total': 15665986, 'state_abbr': 'FL', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9dc')}, {'state': 'Georgia', 'private_cars': 3290675, 'public_cars': 30832, 'total_cars': 3321507, 'private_buses': 9936, 'public_buses': 31854, 'total_buses': 41790, 'private_trucks': 4044313, 'public_trucks': 38178, 'total_trucks': 4082491, 'private_motorcycles': 201206, 'public_motorcycles': 1, 'total_motorcycles': 201207, 'all_private': 7546130, 'all_public': 100865, 'total': 7646995, 'state_abbr': 'GA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9dd')}, {'state': 'Hawaii', 'private_cars': 510652, 'public_cars': 11152, 'total_cars': 521804, 'private_buses': 1841, 'public_buses': 725, 'total_buses': 2566, 'private_trucks': 660766, 'public_trucks': 11079, 'total_trucks': 671845, 'private_motorcycles': 35150, 'public_motorcycles': 377, 'total_motorcycles': 35527, 'all_private': 1208409, 'all_public': 23333, 'total': 1231742, 'state_abbr': 'HI', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9de')}, {'state': 'Idaho', 'private_cars': 571308, 'public_cars': 6074, 'total_cars': 577382, 'private_buses': 283, 'public_buses': 2197, 'total_buses': 2480, 'private_trucks': 989250, 'public_trucks': 11151, 'total_trucks': 1000402, 'private_motorcycles': 63911, 'public_motorcycles': 53, 'total_motorcycles': 63964, 'all_private': 1624753, 'all_public': 19476, 'total': 1644228, 'state_abbr': 'ID', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9df')}, {'state': 'Illinois', 'private_cars': 4670581, 'public_cars': 47076, 'total_cars': 4717657, 'private_buses': 3385, 'public_buses': 26959, 'total_buses': 30344, 'private_trucks': 4967267, 'public_trucks': 51960, 'total_trucks': 5019227, 'private_motorcycles': 364655, 'public_motorcycles': 0, 'total_motorcycles': 364655, 'all_private': 10005888, 'all_public': 125995, 'total': 10131883, 'state_abbr': 'IL', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e0')}, {'state': 'Indiana', 'private_cars': 2417986, 'public_cars': 21155, 'total_cars': 2439141, 'private_buses': 2575, 'public_buses': 6179, 'total_buses': 8754, 'private_trucks': 3305956, 'public_trucks': 27412, 'total_trucks': 3333368, 'private_motorcycles': 223103, 'public_motorcycles': 0, 'total_motorcycles': 223103, 'all_private': 5949620, 'all_public': 54746, 'total': 6004366, 'state_abbr': 'IN', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e1')}, {'state': 'Iowa', 'private_cars': 1333056, 'public_cars': 10280, 'total_cars': 1343336, 'private_buses': 3928, 'public_buses': 5327, 'total_buses': 9255, 'private_trucks': 1953804, 'public_trucks': 24592, 'total_trucks': 1978396, 'private_motorcycles': 179733, 'public_motorcycles': 330, 'total_motorcycles': 180063, 'all_private': 3470521, 'all_public': 40529, 'total': 3511050, 'state_abbr': 'IA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e2')}, {'state': 'Kansas', 'private_cars': 945219, 'public_cars': 14499, 'total_cars': 959718, 'private_buses': 2732, 'public_buses': 1988, 'total_buses': 4720, 'private_trucks': 1383283, 'public_trucks': 19932, 'total_trucks': 1403214, 'private_motorcycles': 81578, 'public_motorcycles': 0, 'total_motorcycles': 81578, 'all_private': 2412811, 'all_public': 36419, 'total': 2449230, 'state_abbr': 'KS', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e3')}, {'state': 'Kentucky', 'private_cars': 1517753, 'public_cars': 16166, 'total_cars': 1533919, 'private_buses': 1978, 'public_buses': 7721, 'total_buses': 9699, 'private_trucks': 2006342, 'public_trucks': 20100, 'total_trucks': 2026442, 'private_motorcycles': 100506, 'public_motorcycles': 0, 'total_motorcycles': 100506, 'all_private': 3626580, 'all_public': 43986, 'total': 3670566, 'state_abbr': 'KY', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e4')}, {'state': 'Louisiana', 'private_cars': 1471603, 'public_cars': 28210, 'total_cars': 1499813, 'private_buses': 6633, 'public_buses': 5884, 'total_buses': 12517, 'private_trucks': 2293516, 'public_trucks': 15273, 'total_trucks': 2308789, 'private_motorcycles': 67486, 'public_motorcycles': 811, 'total_motorcycles': 68297, 'all_private': 3839238, 'all_public': 50178, 'total': 3889416, 'state_abbr': 'LA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e5')}, {'state': 'Maine', 'private_cars': 469189, 'public_cars': 5433, 'total_cars': 474622, 'private_buses': 540, 'public_buses': 893, 'total_buses': 1433, 'private_trucks': 643643, 'public_trucks': 7125, 'total_trucks': 650769, 'private_motorcycles': 53267, 'public_motorcycles': 1, 'total_motorcycles': 53268, 'all_private': 1166639, 'all_public': 13453, 'total': 1180092, 'state_abbr': 'ME', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e6')}, {'state': 'Maryland', 'private_cars': 1941886, 'public_cars': 26149, 'total_cars': 1968035, 'private_buses': 6073, 'public_buses': 9614, 'total_buses': 15687, 'private_trucks': 1850586, 'public_trucks': 27120, 'total_trucks': 1877706, 'private_motorcycles': 121230, 'public_motorcycles': 76, 'total_motorcycles': 121306, 'all_private': 3919775, 'all_public': 62959, 'total': 3982734, 'state_abbr': 'MD', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e7')}, {'state': 'Massachusetts', 'private_cars': 2453950, 'public_cars': 27532, 'total_cars': 2481482, 'private_buses': 8521, 'public_buses': 2719, 'total_buses': 11240, 'private_trucks': 2305542, 'public_trucks': 27474, 'total_trucks': 2333016, 'private_motorcycles': 124121, 'public_motorcycles': 0, 'total_motorcycles': 124121, 'all_private': 4892134, 'all_public': 57725, 'total': 4949859, 'state_abbr': 'MA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e8')}, {'state': 'Michigan', 'private_cars': 3376679, 'public_cars': 31990, 'total_cars': 3408669, 'private_buses': 3357, 'public_buses': 5354, 'total_buses': 8711, 'private_trucks': 4074571, 'public_trucks': 39992, 'total_trucks': 4114563, 'private_motorcycles': 266489, 'public_motorcycles': 0, 'total_motorcycles': 266489, 'all_private': 7721096, 'all_public': 77336, 'total': 7798432, 'state_abbr': 'MI', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9e9')}, {'state': 'Minnesota', 'private_cars': 2127475, 'public_cars': 20796, 'total_cars': 2148272, 'private_buses': 5387, 'public_buses': 7270, 'total_buses': 12657, 'private_trucks': 2670596, 'public_trucks': 25714, 'total_trucks': 2696310, 'private_motorcycles': 241768, 'public_motorcycles': 0, 'total_motorcycles': 241768, 'all_private': 5045226, 'all_public': 53781, 'total': 5099007, 'state_abbr': 'MN', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9ea')}, {'state': 'Mississippi', 'private_cars': 835482, 'public_cars': 12186, 'total_cars': 847669, 'private_buses': 1801, 'public_buses': 6086, 'total_buses': 7887, 'private_trucks': 1152114, 'public_trucks': 16206, 'total_trucks': 1168320, 'private_motorcycles': 28264, 'public_motorcycles': 0, 'total_motorcycles': 28264, 'all_private': 2017662, 'all_public': 34478, 'total': 2052140, 'state_abbr': 'MS', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9eb')}, {'state': 'Missouri', 'private_cars': 2375420, 'public_cars': 22933, 'total_cars': 2398353, 'private_buses': 3573, 'public_buses': 2703, 'total_buses': 6276, 'private_trucks': 3074901, 'public_trucks': 29266, 'total_trucks': 3104166, 'private_motorcycles': 175887, 'public_motorcycles': 0, 'total_motorcycles': 175887, 'all_private': 5629780, 'all_public': 54902, 'total': 5684682, 'state_abbr': 'MO', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9ec')}, {'state': 'Montana', 'private_cars': 428335, 'public_cars': 4929, 'total_cars': 433264, 'private_buses': 3404, 'public_buses': 321, 'total_buses': 3725, 'private_trucks': 883298, 'public_trucks': 9448, 'total_trucks': 892746, 'private_motorcycles': 158871, 'public_motorcycles': 2, 'total_motorcycles': 158873, 'all_private': 1473909, 'all_public': 14699, 'total': 1488608, 'state_abbr': 'MT', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9ed')}, {'state': 'Nebraska', 'private_cars': 705329, 'public_cars': 26909, 'total_cars': 732238, 'private_buses': 656, 'public_buses': 3216, 'total_buses': 3872, 'private_trucks': 1084541, 'public_trucks': 14974, 'total_trucks': 1099515, 'private_motorcycles': 52853, 'public_motorcycles': 0, 'total_motorcycles': 52853, 'all_private': 1843379, 'all_public': 45099, 'total': 1888478, 'state_abbr': 'NE', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9ee')}, {'state': 'Nevada', 'private_cars': 923184, 'public_cars': 9621, 'total_cars': 932805, 'private_buses': 656, 'public_buses': 3207, 'total_buses': 3863, 'private_trucks': 1110961, 'public_trucks': 13062, 'total_trucks': 1124022, 'private_motorcycles': 69634, 'public_motorcycles': 7, 'total_motorcycles': 69641, 'all_private': 2104434, 'all_public': 25896, 'total': 2130331, 'state_abbr': 'NV', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9ef')}, {'state': 'New Hampshire', 'private_cars': 554717, 'public_cars': 5699, 'total_cars': 560416, 'private_buses': 1881, 'public_buses': 1475, 'total_buses': 3356, 'private_trucks': 651842, 'public_trucks': 6950, 'total_trucks': 658792, 'private_motorcycles': 79877, 'public_motorcycles': 0, 'total_motorcycles': 79877, 'all_private': 1288317, 'all_public': 14124, 'total': 1302441, 'state_abbr': 'NH', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f0')}, {'state': 'New Jersey', 'private_cars': 3931287, 'public_cars': 39978, 'total_cars': 3971265, 'private_buses': 13002, 'public_buses': 6604, 'total_buses': 19606, 'private_trucks': 3549817, 'public_trucks': 38316, 'total_trucks': 3588133, 'private_motorcycles': 332470, 'public_motorcycles': 0, 'total_motorcycles': 332470, 'all_private': 7826576, 'all_public': 84898, 'total': 7911474, 'state_abbr': 'NJ', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f1')}, {'state': 'New Mexico', 'private_cars': 663677, 'public_cars': 12060, 'total_cars': 675737, 'private_buses': 1020, 'public_buses': 4391, 'total_buses': 5411, 'private_trucks': 1040028, 'public_trucks': 17948, 'total_trucks': 1057976, 'private_motorcycles': 66666, 'public_motorcycles': 0, 'total_motorcycles': 66666, 'all_private': 1771391, 'all_public': 34399, 'total': 1805790, 'state_abbr': 'NM', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f2')}, {'state': 'New York', 'private_cars': 4991599, 'public_cars': 84605, 'total_cars': 5076204, 'private_buses': 15201, 'public_buses': 10483, 'total_buses': 25684, 'private_trucks': 4921072, 'public_trucks': 80371, 'total_trucks': 5001443, 'private_motorcycles': 345409, 'public_motorcycles': 3, 'total_motorcycles': 345412, 'all_private': 10273281, 'all_public': 175463, 'total': 10448743, 'state_abbr': 'NY', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f3')}, {'state': 'North Carolina', 'private_cars': 3407241, 'public_cars': 38124, 'total_cars': 3445365, 'private_buses': 8922, 'public_buses': 29242, 'total_buses': 38164, 'private_trucks': 4076171, 'public_trucks': 33651, 'total_trucks': 4109822, 'private_motorcycles': 199152, 'public_motorcycles': 53, 'total_motorcycles': 199205, 'all_private': 7691485, 'all_public': 101070, 'total': 7792555, 'state_abbr': 'NC', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f4')}, {'state': 'North Dakota', 'private_cars': 245398, 'public_cars': 3783, 'total_cars': 249181, 'private_buses': 1074, 'public_buses': 1461, 'total_buses': 2535, 'private_trucks': 518669, 'public_trucks': 5960, 'total_trucks': 524628, 'private_motorcycles': 34009, 'public_motorcycles': 2, 'total_motorcycles': 34011, 'all_private': 799150, 'all_public': 11205, 'total': 810355, 'state_abbr': 'ND', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f5')}, {'state': 'Ohio', 'private_cars': 4696974, 'public_cars': 41083, 'total_cars': 4738058, 'private_buses': 15431, 'public_buses': 2754, 'total_buses': 18185, 'private_trucks': 4974738, 'public_trucks': 45580, 'total_trucks': 5020317, 'private_motorcycles': 339677, 'public_motorcycles': 11, 'total_motorcycles': 339688, 'all_private': 10026820, 'all_public': 89428, 'total': 10116248, 'state_abbr': 'OH', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f6')}, {'state': 'Oklahoma', 'private_cars': 1347325, 'public_cars': 14013, 'total_cars': 1361339, 'private_buses': 517, 'public_buses': 1429, 'total_buses': 1946, 'private_trucks': 1929047, 'public_trucks': 19924, 'total_trucks': 1948971, 'private_motorcycles': 127679, 'public_motorcycles': 2, 'total_motorcycles': 127681, 'all_private': 3404569, 'all_public': 35369, 'total': 3439937, 'state_abbr': 'OK', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f7')}, {'state': 'Oregon', 'private_cars': 1439867, 'public_cars': 16122, 'total_cars': 1455989, 'private_buses': 1404, 'public_buses': 1774, 'total_buses': 3178, 'private_trucks': 1959199, 'public_trucks': 22748, 'total_trucks': 1981947, 'private_motorcycles': 86123, 'public_motorcycles': 0, 'total_motorcycles': 86123, 'all_private': 3486593, 'all_public': 40644, 'total': 3527237, 'state_abbr': 'OR', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f8')}, {'state': 'Pennsylvania', 'private_cars': 4728296, 'public_cars': 46221, 'total_cars': 4774517, 'private_buses': 18217, 'public_buses': 18762, 'total_buses': 36979, 'private_trucks': 5169948, 'public_trucks': 70687, 'total_trucks': 5240635, 'private_motorcycles': 418572, 'public_motorcycles': 710, 'total_motorcycles': 419282, 'all_private': 10335033, 'all_public': 136380, 'total': 10471413, 'state_abbr': 'PA', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9f9')}, {'state': 'Rhode Island', 'private_cars': 448890, 'public_cars': 7536, 'total_cars': 456426, 'private_buses': 106, 'public_buses': 2076, 'total_buses': 2182, 'private_trucks': 356489, 'public_trucks': 6184, 'total_trucks': 362673, 'private_motorcycles': 32989, 'public_motorcycles': 89, 'total_motorcycles': 33078, 'all_private': 838474, 'all_public': 15885, 'total': 854359, 'state_abbr': 'RI', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9fa')}, {'state': 'South Carolina', 'private_cars': 1695615, 'public_cars': 17239, 'total_cars': 1712854, 'private_buses': 5661, 'public_buses': 11423, 'total_buses': 17084, 'private_trucks': 2033292, 'public_trucks': 21363, 'total_trucks': 2054655, 'private_motorcycles': 111770, 'public_motorcycles': 469, 'total_motorcycles': 112239, 'all_private': 3846338, 'all_public': 50494, 'total': 3896832, 'state_abbr': 'SC', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9fb')}, {'state': 'South Dakota', 'private_cars': 327336, 'public_cars': 4326, 'total_cars': 331662, 'private_buses': 232, 'public_buses': 2048, 'total_buses': 2280, 'private_trucks': 584670, 'public_trucks': 11607, 'total_trucks': 596277, 'private_motorcycles': 72927, 'public_motorcycles': 425, 'total_motorcycles': 73352, 'all_private': 985165, 'all_public': 18406, 'total': 1003571, 'state_abbr': 'SD', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9fc')}, {'state': 'Tennessee', 'private_cars': 2209551, 'public_cars': 23033, 'total_cars': 2232584, 'private_buses': 5780, 'public_buses': 6248, 'total_buses': 12028, 'private_trucks': 2950628, 'public_trucks': 29855, 'total_trucks': 2980483, 'private_motorcycles': 167566, 'public_motorcycles': 0, 'total_motorcycles': 167566, 'all_private': 5333525, 'all_public': 59136, 'total': 5392661, 'state_abbr': 'TN', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9fd')}, {'state': 'Texas', 'private_cars': 7679657, 'public_cars': 142202, 'total_cars': 7821859, 'private_buses': 2545, 'public_buses': 95140, 'total_buses': 97685, 'private_trucks': 11597044, 'public_trucks': 273135, 'total_trucks': 11870179, 'private_motorcycles': 444514, 'public_motorcycles': 3885, 'total_motorcycles': 448399, 'all_private': 19723760, 'all_public': 514362, 'total': 20238122, 'state_abbr': 'TX', 'year': '2012', '_id': ObjectId('5cafd42178a01b3a3c34f9fe')}, {'state': 'Utah', 'private_cars': 823885, 'public_cars

[{'state': 'Alabama', 'private_cars': 2057430, 'public_cars': 17539, 'total_cars': 2074969, 'private_buses': 1333, 'public_buses': 4073, 'total_buses': 5406, 'private_trucks': 2565820, 'public_trucks': 22940, 'total_trucks': 2588760, 'private_motorcycles': 117142, 'public_motorcycles': 942, 'total_motorcycles': 118084, 'all_private': 4741725, 'all_public': 45494, 'total': 4787219, 'state_abbr': 'AL', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa06')}, {'state': 'Alaska', 'private_cars': 197242, 'public_cars': 3800, 'total_cars': 201042, 'private_buses': 2153, 'public_buses': 1387, 'total_buses': 3540, 'private_trucks': 538145, 'public_trucks': 10891, 'total_trucks': 549036, 'private_motorcycles': 32199, 'public_motorcycles': 8, 'total_motorcycles': 32207, 'all_private': 769739, 'all_public': 16086, 'total': 785825, 'state_abbr': 'AK', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa07')}, {'state': 'Arizona', 'private_cars': 2234532, 'public_cars': 22717, 'total_cars': 2257249, 'private_buses': 16034, 'public_buses': 4955, 'total_buses': 20989, 'private_trucks': 2874457, 'public_trucks': 39995, 'total_trucks': 2914452, 'private_motorcycles': 188359, 'public_motorcycles': 1, 'total_motorcycles': 188360, 'all_private': 5313382, 'all_public': 67668, 'total': 5381050, 'state_abbr': 'AZ', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa08')}, {'state': 'Arkansas', 'private_cars': 822009, 'public_cars': 43201, 'total_cars': 865210, 'private_buses': 1296, 'public_buses': 9099, 'total_buses': 10395, 'private_trucks': 1454107, 'public_trucks': 14051, 'total_trucks': 1468158, 'private_motorcycles': 74196, 'public_motorcycles': 0, 'total_motorcycles': 74196, 'all_private': 2351608, 'all_public': 66351, 'total': 2417959, 'state_abbr': 'AR', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa09')}, {'state': 'California', 'private_cars': 13597778, 'public_cars': 224727, 'total_cars': 13822505, 'private_buses': 33690, 'public_buses': 59194, 'total_buses': 92884, 'private_trucks': 13038149, 'public_trucks': 321539, 'total_trucks': 13359688, 'private_motorcycles': 784987, 'public_motorcycles': 14913, 'total_motorcycles': 799900, 'all_private': 27454604, 'all_public': 620373, 'total': 28074977, 'state_abbr': 'CA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0a')}, {'state': 'Colorado', 'private_cars': 1800225, 'public_cars': 19383, 'total_cars': 1819608, 'private_buses': 7641, 'public_buses': 4117, 'total_buses': 11758, 'private_trucks': 2636749, 'public_trucks': 30746, 'total_trucks': 2667495, 'private_motorcycles': 184497, 'public_motorcycles': 52, 'total_motorcycles': 184549, 'all_private': 4629112, 'all_public': 54298, 'total': 4683410, 'state_abbr': 'CO', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0b')}, {'state': 'Connecticut', 'private_cars': 1457906, 'public_cars': 16675, 'total_cars': 1474581, 'private_buses': 3587, 'public_buses': 8792, 'total_buses': 12379, 'private_trucks': 1253168, 'public_trucks': 24356, 'total_trucks': 1277524, 'private_motorcycles': 91054, 'public_motorcycles': 0, 'total_motorcycles': 91054, 'all_private': 2805715, 'all_public': 49823, 'total': 2855538, 'state_abbr': 'CT', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0c')}, {'state': 'Delaware', 'private_cars': 447337, 'public_cars': 818, 'total_cars': 448155, 'private_buses': 2635, 'public_buses': 1872, 'total_buses': 4507, 'private_trucks': 461493, 'public_trucks': 3231, 'total_trucks': 464724, 'private_motorcycles': 30056, 'public_motorcycles': 0, 'total_motorcycles': 30056, 'all_private': 941521, 'all_public': 5921, 'total': 947442, 'state_abbr': 'DE', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0d')}, {'state': 'Florida', 'private_cars': 7309847, 'public_cars': 115645, 'total_cars': 7425492, 'private_buses': 25409, 'public_buses': 33335, 'total_buses': 58744, 'private_trucks': 6985473, 'public_trucks': 116574, 'total_trucks': 7102047, 'private_motorcycles': 542988, 'public_motorcycles': 2464, 'total_motorcycles': 545452, 'all_private': 14863717, 'all_public': 268018, 'total': 15131735, 'state_abbr': 'FL', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0e')}, {'state': 'Georgia', 'private_cars': 3405052, 'public_cars': 29988, 'total_cars': 3435040, 'private_buses': 10203, 'public_buses': 31573, 'total_buses': 41776, 'private_trucks': 4066201, 'public_trucks': 37196, 'total_trucks': 4103397, 'private_motorcycles': 199287, 'public_motorcycles': 846, 'total_motorcycles': 200133, 'all_private': 7680743, 'all_public': 99603, 'total': 7780346, 'state_abbr': 'GA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa0f')}, {'state': 'Hawaii', 'private_cars': 556832, 'public_cars': 11406, 'total_cars': 568238, 'private_buses': 2139, 'public_buses': 893, 'total_buses': 3032, 'private_trucks': 712457, 'public_trucks': 10401, 'total_trucks': 722858, 'private_motorcycles': 40194, 'public_motorcycles': 370, 'total_motorcycles': 40564, 'all_private': 1311622, 'all_public': 23070, 'total': 1334692, 'state_abbr': 'HI', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa10')}, {'state': 'Idaho', 'private_cars': 594469, 'public_cars': 4408, 'total_cars': 598877, 'private_buses': 2630, 'public_buses': 502, 'total_buses': 3132, 'private_trucks': 1020334, 'public_trucks': 5170, 'total_trucks': 1025504, 'private_motorcycles': 64899, 'public_motorcycles': 45, 'total_motorcycles': 64944, 'all_private': 1682332, 'all_public': 10125, 'total': 1692457, 'state_abbr': 'ID', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa11')}, {'state': 'Illinois', 'private_cars': 4750367, 'public_cars': 46625, 'total_cars': 4796992, 'private_buses': 3744, 'public_buses': 29827, 'total_buses': 33571, 'private_trucks': 4958606, 'public_trucks': 51951, 'total_trucks': 5010557, 'private_motorcycles': 352318, 'public_motorcycles': 0, 'total_motorcycles': 352318, 'all_private': 10065035, 'all_public': 128403, 'total': 10193438, 'state_abbr': 'IL', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa12')}, {'state': 'Indiana', 'private_cars': 2256724, 'public_cars': 8181, 'total_cars': 2264905, 'private_buses': 9291, 'public_buses': 870, 'total_buses': 10161, 'private_trucks': 3073698, 'public_trucks': 6632, 'total_trucks': 3080330, 'private_motorcycles': 218594, 'public_motorcycles': 36, 'total_motorcycles': 218630, 'all_private': 5558307, 'all_public': 15719, 'total': 5574026, 'state_abbr': 'IN', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa13')}, {'state': 'Iowa', 'private_cars': 1356198, 'public_cars': 10191, 'total_cars': 1366389, 'private_buses': 3929, 'public_buses': 5336, 'total_buses': 9265, 'private_trucks': 1957267, 'public_trucks': 24548, 'total_trucks': 1981815, 'private_motorcycles': 182964, 'public_motorcycles': 330, 'total_motorcycles': 183294, 'all_private': 3500358, 'all_public': 40405, 'total': 3540763, 'state_abbr': 'IA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa14')}, {'state': 'Kansas', 'private_cars': 1016853, 'public_cars': 14381, 'total_cars': 1031234, 'private_buses': 2879, 'public_buses': 2000, 'total_buses': 4879, 'private_trucks': 1472639, 'public_trucks': 19924, 'total_trucks': 1492563, 'private_motorcycles': 99169, 'public_motorcycles': 0, 'total_motorcycles': 99169, 'all_private': 2591540, 'all_public': 36305, 'total': 2627845, 'state_abbr': 'KS', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa15')}, {'state': 'Kentucky', 'private_cars': 1698845, 'public_cars': 16059, 'total_cars': 1714904, 'private_buses': 2027, 'public_buses': 7720, 'total_buses': 9747, 'private_trucks': 2177396, 'public_trucks': 19880, 'total_trucks': 2197276, 'private_motorcycles': 109821, 'public_motorcycles': 0, 'total_motorcycles': 109821, 'all_private': 3988089, 'all_public': 43659, 'total': 4031748, 'state_abbr': 'KY', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa16')}, {'state': 'Louisiana', 'private_cars': 1466291, 'public_cars': 40213, 'total_cars': 1506504, 'private_buses': 22016, 'public_buses': 6959, 'total_buses': 28975, 'private_trucks': 2269301, 'public_trucks': 38616, 'total_trucks': 2307917, 'private_motorcycles': 112967, 'public_motorcycles': 811, 'total_motorcycles': 113778, 'all_private': 3870575, 'all_public': 86599, 'total': 3957174, 'state_abbr': 'LA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa17')}, {'state': 'Maine', 'private_cars': 482461, 'public_cars': 5435, 'total_cars': 487896, 'private_buses': 647, 'public_buses': 886, 'total_buses': 1533, 'private_trucks': 639444, 'public_trucks': 7147, 'total_trucks': 646591, 'private_motorcycles': 63113, 'public_motorcycles': 1, 'total_motorcycles': 63114, 'all_private': 1185665, 'all_public': 13469, 'total': 1199134, 'state_abbr': 'ME', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa18')}, {'state': 'Maryland', 'private_cars': 1892687, 'public_cars': 25919, 'total_cars': 1918606, 'private_buses': 6134, 'public_buses': 9692, 'total_buses': 15826, 'private_trucks': 1772598, 'public_trucks': 26936, 'total_trucks': 1799534, 'private_motorcycles': 99484, 'public_motorcycles': 76, 'total_motorcycles': 99560, 'all_private': 3770903, 'all_public': 62623, 'total': 3833526, 'state_abbr': 'MD', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa19')}, {'state': 'Massachusetts', 'private_cars': 2482874, 'public_cars': 27906, 'total_cars': 2510780, 'private_buses': 8259, 'public_buses': 2790, 'total_buses': 11049, 'private_trucks': 2310653, 'public_trucks': 27844, 'total_trucks': 2338497, 'private_motorcycles': 125009, 'public_motorcycles': 113, 'total_motorcycles': 125122, 'all_private': 4926795, 'all_public': 58653, 'total': 4985448, 'state_abbr': 'MA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1a')}, {'state': 'Michigan', 'private_cars': 3562296, 'public_cars': 31455, 'total_cars': 3593751, 'private_buses': 3391, 'public_buses': 5295, 'total_buses': 8686, 'private_trucks': 4282897, 'public_trucks': 39742, 'total_trucks': 4322639, 'private_motorcycles': 267292, 'public_motorcycles': 0, 'total_motorcycles': 267292, 'all_private': 8115876, 'all_public': 76492, 'total': 8192368, 'state_abbr': 'MI', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1b')}, {'state': 'Minnesota', 'private_cars': 2191480, 'public_cars': 20926, 'total_cars': 2212406, 'private_buses': 5188, 'public_buses': 7250, 'total_buses': 12438, 'private_trucks': 2731557, 'public_trucks': 25830, 'total_trucks': 2757387, 'private_motorcycles': 237259, 'public_motorcycles': 0, 'total_motorcycles': 237259, 'all_private': 5165484, 'all_public': 54006, 'total': 5219490, 'state_abbr': 'MN', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1c')}, {'state': 'Mississippi', 'private_cars': 867834, 'public_cars': 3972, 'total_cars': 871806, 'private_buses': 1976, 'public_buses': 6080, 'total_buses': 8056, 'private_trucks': 1159201, 'public_trucks': 6039, 'total_trucks': 1165240, 'private_motorcycles': 28433, 'public_motorcycles': 0, 'total_motorcycles': 28433, 'all_private': 2057444, 'all_public': 16091, 'total': 2073535, 'state_abbr': 'MS', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1d')}, {'state': 'Missouri', 'private_cars': 2462175, 'public_cars': 22729, 'total_cars': 2484904, 'private_buses': 3118, 'public_buses': 2340, 'total_buses': 5458, 'private_trucks': 3116365, 'public_trucks': 29206, 'total_trucks': 3145571, 'private_motorcycles': 184723, 'public_motorcycles': 0, 'total_motorcycles': 184723, 'all_private': 5766381, 'all_public': 54275, 'total': 5820656, 'state_abbr': 'MO', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1e')}, {'state': 'Montana', 'private_cars': 441896, 'public_cars': 2811, 'total_cars': 444707, 'private_buses': 4275, 'public_buses': 153, 'total_buses': 4428, 'private_trucks': 915542, 'public_trucks': 4169, 'total_trucks': 919711, 'private_motorcycles': 171083, 'public_motorcycles': 2, 'total_motorcycles': 171085, 'all_private': 1532796, 'all_public': 7135, 'total': 1539931, 'state_abbr': 'MT', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa1f')}, {'state': 'Nebraska', 'private_cars': 703558, 'public_cars': 29450, 'total_cars': 733008, 'private_buses': 2435, 'public_buses': 1395, 'total_buses': 3830, 'private_trucks': 1081752, 'public_trucks': 16439, 'total_trucks': 1098191, 'private_motorcycles': 56224, 'public_motorcycles': 0, 'total_motorcycles': 56224, 'all_private': 1843969, 'all_public': 47284, 'total': 1891253, 'state_abbr': 'NE', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa20')}, {'state': 'Nevada', 'private_cars': 968310, 'public_cars': 9542, 'total_cars': 977852, 'private_buses': 702, 'public_buses': 3236, 'total_buses': 3938, 'private_trucks': 1137615, 'public_trucks': 13016, 'total_trucks': 1150631, 'private_motorcycles': 70670, 'public_motorcycles': 5, 'total_motorcycles': 70675, 'all_private': 2177297, 'all_public': 25799, 'total': 2203096, 'state_abbr': 'NV', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa21')}, {'state': 'New Hampshire', 'private_cars': 619735, 'public_cars': 5656, 'total_cars': 625391, 'private_buses': 1881, 'public_buses': 643, 'total_buses': 2524, 'private_trucks': 702159, 'public_trucks': 5250, 'total_trucks': 707409, 'private_motorcycles': 73612, 'public_motorcycles': 0, 'total_motorcycles': 73612, 'all_private': 1397387, 'all_public': 11549, 'total': 1408936, 'state_abbr': 'NH', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa22')}, {'state': 'New Jersey', 'private_cars': 3603866, 'public_cars': 40680, 'total_cars': 3644546, 'private_buses': 14364, 'public_buses': 5881, 'total_buses': 20245, 'private_trucks': 3213690, 'public_trucks': 30751, 'total_trucks': 3244441, 'private_motorcycles': 152111, 'public_motorcycles': 0, 'total_motorcycles': 152111, 'all_private': 6984031, 'all_public': 77312, 'total': 7061343, 'state_abbr': 'NJ', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa23')}, {'state': 'New Mexico', 'private_cars': 704593, 'public_cars': 11846, 'total_cars': 716439, 'private_buses': 1062, 'public_buses': 4398, 'total_buses': 5460, 'private_trucks': 1077482, 'public_trucks': 17764, 'total_trucks': 1095246, 'private_motorcycles': 65321, 'public_motorcycles': 0, 'total_motorcycles': 65321, 'all_private': 1848458, 'all_public': 34008, 'total': 1882466, 'state_abbr': 'NM', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa24')}, {'state': 'New York', 'private_cars': 5119508, 'public_cars': 83849, 'total_cars': 5203357, 'private_buses': 15323, 'public_buses': 10416, 'total_buses': 25738, 'private_trucks': 5019930, 'public_trucks': 79991, 'total_trucks': 5099921, 'private_motorcycles': 345116, 'public_motorcycles': 2, 'total_motorcycles': 345118, 'all_private': 10499877, 'all_public': 174258, 'total': 10674135, 'state_abbr': 'NY', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa25')}, {'state': 'North Carolina', 'private_cars': 3462557, 'public_cars': 33247, 'total_cars': 3495804, 'private_buses': 11530, 'public_buses': 19748, 'total_buses': 31278, 'private_trucks': 4060835, 'public_trucks': 30444, 'total_trucks': 4091279, 'private_motorcycles': 195479, 'public_motorcycles': 14, 'total_motorcycles': 195493, 'all_private': 7730401, 'all_public': 83453, 'total': 7813854, 'state_abbr': 'NC', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa26')}, {'state': 'North Dakota', 'private_cars': 248971, 'public_cars': 6212, 'total_cars': 255183, 'private_buses': 956, 'public_buses': 1665, 'total_buses': 2621, 'private_trucks': 541680, 'public_trucks': 9869, 'total_trucks': 551549, 'private_motorcycles': 35742, 'public_motorcycles': 14, 'total_motorcycles': 35756, 'all_private': 827349, 'all_public': 17760, 'total': 845109, 'state_abbr': 'ND', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa27')}, {'state': 'Ohio', 'private_cars': 4806463, 'public_cars': 56305, 'total_cars': 4862768, 'private_buses': 17337, 'public_buses': 24632, 'total_buses': 41969, 'private_trucks': 4993077, 'public_trucks': 60287, 'total_trucks': 5053364, 'private_motorcycles': 402247, 'public_motorcycles': 17, 'total_motorcycles': 402264, 'all_private': 10219124, 'all_public': 141241, 'total': 10360365, 'state_abbr': 'OH', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa28')}, {'state': 'Oklahoma', 'private_cars': 1359390, 'public_cars': 16728, 'total_cars': 1376118, 'private_buses': 503, 'public_buses': 1610, 'total_buses': 2113, 'private_trucks': 1939271, 'public_trucks': 15627, 'total_trucks': 1954898, 'private_motorcycles': 126882, 'public_motorcycles': 1, 'total_motorcycles': 126883, 'all_private': 3426046, 'all_public': 33966, 'total': 3460012, 'state_abbr': 'OK', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa29')}, {'state': 'Oregon', 'private_cars': 1504916, 'public_cars': 15868, 'total_cars': 1520784, 'private_buses': 1412, 'public_buses': 1766, 'total_buses': 3178, 'private_trucks': 1967562, 'public_trucks': 22504, 'total_trucks': 1990066, 'private_motorcycles': 89797, 'public_motorcycles': 0, 'total_motorcycles': 89797, 'all_private': 3563687, 'all_public': 40138, 'total': 3603825, 'state_abbr': 'OR', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2a')}, {'state': 'Pennsylvania', 'private_cars': 4763611, 'public_cars': 46289, 'total_cars': 4809900, 'private_buses': 51850, 'public_buses': 2653, 'total_buses': 54503, 'private_trucks': 5124466, 'public_trucks': 71331, 'total_trucks': 5195797, 'private_motorcycles': 400183, 'public_motorcycles': 725, 'total_motorcycles': 400908, 'all_private': 10340110, 'all_public': 120998, 'total': 10461108, 'state_abbr': 'PA', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2b')}, {'state': 'Rhode Island', 'private_cars': 451775, 'public_cars': 7618, 'total_cars': 459393, 'private_buses': 106, 'public_buses': 2009, 'total_buses': 2115, 'private_trucks': 353028, 'public_trucks': 6364, 'total_trucks': 359392, 'private_motorcycles': 32159, 'public_motorcycles': 93, 'total_motorcycles': 32252, 'all_private': 837068, 'all_public': 16084, 'total': 853152, 'state_abbr': 'RI', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2c')}, {'state': 'South Carolina', 'private_cars': 1709013, 'public_cars': 41629, 'total_cars': 1750642, 'private_buses': 5408, 'public_buses': 12672, 'total_buses': 18080, 'private_trucks': 2062766, 'public_trucks': 41771, 'total_trucks': 2104537, 'private_motorcycles': 112851, 'public_motorcycles': 464, 'total_motorcycles': 113315, 'all_private': 3890038, 'all_public': 96536, 'total': 3986574, 'state_abbr': 'SC', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2d')}, {'state': 'South Dakota', 'private_cars': 325944, 'public_cars': 5976, 'total_cars': 331920, 'private_buses': 232, 'public_buses': 2460, 'total_buses': 2692, 'private_trucks': 577916, 'public_trucks': 15935, 'total_trucks': 593851, 'private_motorcycles': 86197, 'public_motorcycles': 513, 'total_motorcycles': 86710, 'all_private': 990289, 'all_public': 24884, 'total': 1015173, 'state_abbr': 'SD', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2e')}, {'state': 'Tennessee', 'private_cars': 2248204, 'public_cars': 36122, 'total_cars': 2284326, 'private_buses': 2104, 'public_buses': 23706, 'total_buses': 25810, 'private_trucks': 2894820, 'public_trucks': 83157, 'total_trucks': 2977977, 'private_motorcycles': 163820, 'public_motorcycles': 0, 'total_motorcycles': 163820, 'all_private': 5308948, 'all_public': 142985, 'total': 5451933, 'state_abbr': 'TN', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa2f')}, {'state': 'Texas', 'private_cars': 7810175, 'public_cars': 144731, 'total_cars': 7954906, 'private_buses': 18347, 'public_buses': 81135, 'total_buses': 99482, 'private_trucks': 11392993, 'public_trucks': 279898, 'total_trucks': 11672891, 'private_motorcycles': 439885, 'public_motorcycles': 3971, 'total_motorcycles': 443856, 'all_private': 19661400, 'all_public': 509735, 'total': 20171135, 'state_abbr': 'TX', 'year': '2013', '_id': ObjectId('5cafd42178a01b3a3c34fa30')}, {'state': 'Utah', 'private_cars': 868993, 'p

[{'state': 'Alabama', 'private_cars': 2506496, 'public_cars': 17649, 'total_cars': 2524145, 'private_buses': 1261.0, 'public_buses': 4136, 'total_buses': 5397, 'private_trucks': 2698310, 'public_trucks': 23224, 'total_trucks': 2721534, 'private_motorcycles': 114843, 'public_motorcycles': 925.0, 'total_motorcycles': 115768, 'all_private': 5320910, 'all_public': 45934, 'total': 5366844, 'state_abbr': 'AL', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa38')}, {'state': 'Alaska', 'private_cars': 191706, 'public_cars': 3683, 'total_cars': 195389, 'private_buses': 2124.0, 'public_buses': 1374, 'total_buses': 3498, 'private_trucks': 558874, 'public_trucks': 10582, 'total_trucks': 569456, 'private_motorcycles': 32082, 'public_motorcycles': 8.0, 'total_motorcycles': 32090, 'all_private': 784786, 'all_public': 15647, 'total': 800433, 'state_abbr': 'AK', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa39')}, {'state': 'Arizona', 'private_cars': 2298039, 'public_cars': 22625, 'total_cars': 2320664, 'private_buses': 16034.0, 'public_buses': 5008, 'total_buses': 21042, 'private_trucks': 3025292, 'public_trucks': 40100, 'total_trucks': 3065391, 'private_motorcycles': 180913, 'public_motorcycles': 4.0, 'total_motorcycles': 180917, 'all_private': 5520278, 'all_public': 67737, 'total': 5588014, 'state_abbr': 'AZ', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3a')}, {'state': 'Arkansas', 'private_cars': 954536, 'public_cars': 34755, 'total_cars': 989291, 'private_buses': 10847.0, 'public_buses': 689, 'total_buses': 11536, 'private_trucks': 1671001, 'public_trucks': 13911, 'total_trucks': 1684913, 'private_motorcycles': 92921, 'public_motorcycles': 0.0, 'total_motorcycles': 92921, 'all_private': 2729305, 'all_public': 49355, 'total': 2778660, 'state_abbr': 'AR', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3b')}, {'state': 'California', 'private_cars': 13789501, 'public_cars': 276488, 'total_cars': 14065989, 'private_buses': 33934.0, 'public_buses': 59130, 'total_buses': 93064, 'private_trucks': 13320923, 'public_trucks': 392899, 'total_trucks': 13713822, 'private_motorcycles': 799006, 'public_motorcycles': 14765.0, 'total_motorcycles': 813771, 'all_private': 27943364, 'all_public': 743282, 'total': 28686646, 'state_abbr': 'CA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3c')}, {'state': 'Colorado', 'private_cars': 1786643, 'public_cars': 19842, 'total_cars': 1806485, 'private_buses': 6025.0, 'public_buses': 6008, 'total_buses': 12033, 'private_trucks': 2782392, 'public_trucks': 31520, 'total_trucks': 2813912, 'private_motorcycles': 188136, 'public_motorcycles': 56.0, 'total_motorcycles': 188192, 'all_private': 4763196, 'all_public': 57426, 'total': 4820622, 'state_abbr': 'CO', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3d')}, {'state': 'Connecticut', 'private_cars': 1414217, 'public_cars': 16683, 'total_cars': 1430900, 'private_buses': 12444.0, 'public_buses': 163, 'total_buses': 12607, 'private_trucks': 1309198, 'public_trucks': 24423, 'total_trucks': 1333621, 'private_motorcycles': 89332, 'public_motorcycles': 0.0, 'total_motorcycles': 89332, 'all_private': 2825191, 'all_public': 41269, 'total': 2866460, 'state_abbr': 'CT', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3e')}, {'state': 'Delaware', 'private_cars': 440929, 'public_cars': 816, 'total_cars': 441745, 'private_buses': 4036.0, 'public_buses': 469, 'total_buses': 4505, 'private_trucks': 478091, 'public_trucks': 2935, 'total_trucks': 481026, 'private_motorcycles': 30393, 'public_motorcycles': 0.0, 'total_motorcycles': 30393, 'all_private': 953449, 'all_public': 4220, 'total': 957669, 'state_abbr': 'DE', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa3f')}, {'state': 'Florida', 'private_cars': 7426955, 'public_cars': 116935, 'total_cars': 7543890, 'private_buses': 26657.0, 'public_buses': 33321, 'total_buses': 59978, 'private_trucks': 7225075, 'public_trucks': 117748, 'total_trucks': 7342823, 'private_motorcycles': 555602, 'public_motorcycles': 2521.0, 'total_motorcycles': 558123, 'all_private': 15234289, 'all_public': 270525, 'total': 15504814, 'state_abbr': 'FL', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa40')}, {'state': 'Georgia', 'private_cars': 3509347, 'public_cars': 58541, 'total_cars': 3567888, 'private_buses': 21079.0, 'public_buses': 20364, 'total_buses': 41443, 'private_trucks': 4276140, 'public_trucks': 70061, 'total_trucks': 4346201, 'private_motorcycles': 199445, 'public_motorcycles': 130.0, 'total_motorcycles': 199575, 'all_private': 8006011, 'all_public': 149096, 'total': 8155107, 'state_abbr': 'GA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa41')}, {'state': 'Hawaii', 'private_cars': 580384, 'public_cars': 11587, 'total_cars': 591971, 'private_buses': 2097.0, 'public_buses': 833, 'total_buses': 2930, 'private_trucks': 745078, 'public_trucks': 10459, 'total_trucks': 755537, 'private_motorcycles': 42450, 'public_motorcycles': 371.0, 'total_motorcycles': 42821, 'all_private': 1370009, 'all_public': 23250, 'total': 1393259, 'state_abbr': 'HI', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa42')}, {'state': 'Idaho', 'private_cars': 604193, 'public_cars': 4478, 'total_cars': 608671, 'private_buses': 2880.0, 'public_buses': 524, 'total_buses': 3404, 'private_trucks': 1079351, 'public_trucks': 5070, 'total_trucks': 1084421, 'private_motorcycles': 66149, 'public_motorcycles': 42.0, 'total_motorcycles': 66191, 'all_private': 1752573, 'all_public': 10114, 'total': 1762687, 'state_abbr': 'ID', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa43')}, {'state': 'Illinois', 'private_cars': 4748735, 'public_cars': 46645, 'total_cars': 4795380, 'private_buses': 30666.0, 'public_buses': 216, 'total_buses': 30882, 'private_trucks': 5164160, 'public_trucks': 51783, 'total_trucks': 5215943, 'private_motorcycles': 351277, 'public_motorcycles': 21.0, 'total_motorcycles': 351298, 'all_private': 10294838, 'all_public': 98665, 'total': 10393503, 'state_abbr': 'IL', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa44')}, {'state': 'Indiana', 'private_cars': 2390631, 'public_cars': 5128, 'total_cars': 2395759, 'private_buses': 8320.0, 'public_buses': 755, 'total_buses': 9075, 'private_trucks': 3378592, 'public_trucks': 6514, 'total_trucks': 3385106, 'private_motorcycles': 222634, 'public_motorcycles': 21.0, 'total_motorcycles': 222655, 'all_private': 6000177, 'all_public': 12418, 'total': 6012595, 'state_abbr': 'IN', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa45')}, {'state': 'Iowa', 'private_cars': 1339065, 'public_cars': 10228, 'total_cars': 1349293, 'private_buses': 3501.0, 'public_buses': 5339, 'total_buses': 8840, 'private_trucks': 2026560, 'public_trucks': 24586, 'total_trucks': 2051146, 'private_motorcycles': 186921, 'public_motorcycles': 330.0, 'total_motorcycles': 187251, 'all_private': 3556047, 'all_public': 40483, 'total': 3596530, 'state_abbr': 'IA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa46')}, {'state': 'Kansas', 'private_cars': 964102, 'public_cars': 14509, 'total_cars': 978612, 'private_buses': 1428.0, 'public_buses': 1998, 'total_buses': 3426, 'private_trucks': 1443946, 'public_trucks': 19878, 'total_trucks': 1463824, 'private_motorcycles': 96817, 'public_motorcycles': 0.0, 'total_motorcycles': 96817, 'all_private': 2506293, 'all_public': 36385, 'total': 2542678, 'state_abbr': 'KS', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa47')}, {'state': 'Kentucky', 'private_cars': 1733912, 'public_cars': 16067, 'total_cars': 1749979, 'private_buses': 1992.0, 'public_buses': 7698, 'total_buses': 9690, 'private_trucks': 2258038, 'public_trucks': 19917, 'total_trucks': 2277955, 'private_motorcycles': 111096, 'public_motorcycles': 0.0, 'total_motorcycles': 111096, 'all_private': 4105038, 'all_public': 43682, 'total': 4148721, 'state_abbr': 'KY', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa48')}, {'state': 'Louisiana', 'private_cars': 1420906, 'public_cars': 38434, 'total_cars': 1459340, 'private_buses': 26166.0, 'public_buses': 6903, 'total_buses': 33069, 'private_trucks': 2239788, 'public_trucks': 40495, 'total_trucks': 2280283, 'private_motorcycles': 113778, 'public_motorcycles': 464.0, 'total_motorcycles': 114242, 'all_private': 3800638, 'all_public': 86296, 'total': 3886934, 'state_abbr': 'LA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa49')}, {'state': 'Maine', 'private_cars': 466377, 'public_cars': 5339, 'total_cars': 471717, 'private_buses': 1940.0, 'public_buses': 1922, 'total_buses': 3862, 'private_trucks': 660479, 'public_trucks': 6980, 'total_trucks': 667459, 'private_motorcycles': 51622, 'public_motorcycles': 1.0, 'total_motorcycles': 51623, 'all_private': 1180418, 'all_public': 14243, 'total': 1194661, 'state_abbr': 'ME', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4a')}, {'state': 'Maryland', 'private_cars': 1945895, 'public_cars': 43921, 'total_cars': 1989816, 'private_buses': 7314.0, 'public_buses': 4078, 'total_buses': 11392, 'private_trucks': 1879645, 'public_trucks': 45954, 'total_trucks': 1925599, 'private_motorcycles': 125207, 'public_motorcycles': 76.0, 'total_motorcycles': 125283, 'all_private': 3958061, 'all_public': 94029, 'total': 4052090, 'state_abbr': 'MD', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4b')}, {'state': 'Massachusetts', 'private_cars': 2409923, 'public_cars': 28331, 'total_cars': 2438254, 'private_buses': 10380.0, 'public_buses': 2844, 'total_buses': 13224, 'private_trucks': 2389263, 'public_trucks': 28429, 'total_trucks': 2417692, 'private_motorcycles': 125157, 'public_motorcycles': 113.0, 'total_motorcycles': 125270, 'all_private': 4934722, 'all_public': 59717, 'total': 4994439, 'state_abbr': 'MA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4c')}, {'state': 'Michigan', 'private_cars': 3414399, 'public_cars': 31408, 'total_cars': 3445807, 'private_buses': 3368.0, 'public_buses': 5273, 'total_buses': 8640, 'private_trucks': 4373940, 'public_trucks': 39537, 'total_trucks': 4413477, 'private_motorcycles': 258413, 'public_motorcycles': 0.0, 'total_motorcycles': 258413, 'all_private': 8050120, 'all_public': 76218, 'total': 8126337, 'state_abbr': 'MI', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4d')}, {'state': 'Minnesota', 'private_cars': 2141437, 'public_cars': 20967, 'total_cars': 2162403, 'private_buses': 5397.0, 'public_buses': 7303, 'total_buses': 12700, 'private_trucks': 2784682, 'public_trucks': 25997, 'total_trucks': 2810679, 'private_motorcycles': 237408, 'public_motorcycles': 0.0, 'total_motorcycles': 237408, 'all_private': 5168923, 'all_public': 54266, 'total': 5223189, 'state_abbr': 'MN', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4e')}, {'state': 'Mississippi', 'private_cars': 853699, 'public_cars': 3968, 'total_cars': 857667, 'private_buses': 1831.0, 'public_buses': 6079, 'total_buses': 7910, 'private_trucks': 1167660, 'public_trucks': 6095, 'total_trucks': 1173755, 'private_motorcycles': 28474, 'public_motorcycles': 0.0, 'total_motorcycles': 28474, 'all_private': 2051664, 'all_public': 16142, 'total': 2067806, 'state_abbr': 'MS', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa4f')}, {'state': 'Missouri', 'private_cars': 2208671, 'public_cars': 22623, 'total_cars': 2231294, 'private_buses': 3543.0, 'public_buses': 2358, 'total_buses': 5901, 'private_trucks': 2912386, 'public_trucks': 29521, 'total_trucks': 2941907, 'private_motorcycles': 153799, 'public_motorcycles': 0.0, 'total_motorcycles': 153799, 'all_private': 5278399, 'all_public': 54502, 'total': 5332901, 'state_abbr': 'MO', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa50')}, {'state': 'Montana', 'private_cars': 433476, 'public_cars': 3105, 'total_cars': 436581, 'private_buses': 4339.0, 'public_buses': 155, 'total_buses': 4494, 'private_trucks': 956517, 'public_trucks': 4344, 'total_trucks': 960861, 'private_motorcycles': 183892, 'public_motorcycles': 2.0, 'total_motorcycles': 183894, 'all_private': 1578224, 'all_public': 7606, 'total': 1585830, 'state_abbr': 'MT', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa51')}, {'state': 'Nebraska', 'private_cars': 723979, 'public_cars': 27565, 'total_cars': 751544, 'private_buses': 3859.0, 'public_buses': 72, 'total_buses': 3931, 'private_trucks': 1124356, 'public_trucks': 15279, 'total_trucks': 1139635, 'private_motorcycles': 52517, 'public_motorcycles': 0.0, 'total_motorcycles': 52517, 'all_private': 1904711, 'all_public': 42916, 'total': 1947627, 'state_abbr': 'NE', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa52')}, {'state': 'Nevada', 'private_cars': 980445, 'public_cars': 9668, 'total_cars': 990113, 'private_buses': 696.0, 'public_buses': 3274, 'total_buses': 3970, 'private_trucks': 1161393, 'public_trucks': 13141, 'total_trucks': 1174534, 'private_motorcycles': 71875, 'public_motorcycles': 5.0, 'total_motorcycles': 71880, 'all_private': 2214410, 'all_public': 26088, 'total': 2240498, 'state_abbr': 'NV', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa53')}, {'state': 'New Hampshire', 'private_cars': 553375, 'public_cars': 5799, 'total_cars': 559174, 'private_buses': 653.0, 'public_buses': 2165, 'total_buses': 2818, 'private_trucks': 666745, 'public_trucks': 5361, 'total_trucks': 672105, 'private_motorcycles': 76093, 'public_motorcycles': 0.0, 'total_motorcycles': 76093, 'all_private': 1296866, 'all_public': 13325, 'total': 1310191, 'state_abbr': 'NH', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa54')}, {'state': 'New Jersey', 'private_cars': 3419992, 'public_cars': 56354, 'total_cars': 3476346, 'private_buses': 23718.0, 'public_buses': 111, 'total_buses': 23829, 'private_trucks': 3183877, 'public_trucks': 40085, 'total_trucks': 3223962, 'private_motorcycles': 149963, 'public_motorcycles': 0.0, 'total_motorcycles': 149963, 'all_private': 6777550, 'all_public': 96550, 'total': 6874100, 'state_abbr': 'NJ', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa55')}, {'state': 'New Mexico', 'private_cars': 712265, 'public_cars': 11834, 'total_cars': 724099, 'private_buses': 5912.0, 'public_buses': 1136, 'total_buses': 7048, 'private_trucks': 1116904, 'public_trucks': 18057, 'total_trucks': 1134961, 'private_motorcycles': 64598, 'public_motorcycles': 0.0, 'total_motorcycles': 64598, 'all_private': 1899679, 'all_public': 31027, 'total': 1930706, 'state_abbr': 'NM', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa56')}, {'state': 'New York', 'private_cars': 5132288, 'public_cars': 27408, 'total_cars': 5159696, 'private_buses': 21220.0, 'public_buses': 4952, 'total_buses': 26172, 'private_trucks': 5351168, 'public_trucks': 20374, 'total_trucks': 5371542, 'private_motorcycles': 345116, 'public_motorcycles': 1094.0, 'total_motorcycles': 346210, 'all_private': 10849792, 'all_public': 53828, 'total': 10903620, 'state_abbr': 'NY', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa57')}, {'state': 'North Carolina', 'private_cars': 3403864, 'public_cars': 70904, 'total_cars': 3474768, 'private_buses': 11578.0, 'public_buses': 19740, 'total_buses': 31318, 'private_trucks': 4132194, 'public_trucks': 44107, 'total_trucks': 4176301, 'private_motorcycles': 193386, 'public_motorcycles': 257.0, 'total_motorcycles': 193643, 'all_private': 7741022, 'all_public': 135008, 'total': 7876030, 'state_abbr': 'NC', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa58')}, {'state': 'North Dakota', 'private_cars': 244548, 'public_cars': 6451, 'total_cars': 250998, 'private_buses': 935.0, 'public_buses': 1757, 'total_buses': 2692, 'private_trucks': 569188, 'public_trucks': 10605, 'total_trucks': 579794, 'private_motorcycles': 37234, 'public_motorcycles': 13.0, 'total_motorcycles': 37247, 'all_private': 851905, 'all_public': 18826, 'total': 870731, 'state_abbr': 'ND', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa59')}, {'state': 'Ohio', 'private_cars': 4751891, 'public_cars': 54868, 'total_cars': 4806759, 'private_buses': 32232.0, 'public_buses': 7549, 'total_buses': 39781, 'private_trucks': 5143010, 'public_trucks': 59038, 'total_trucks': 5202048, 'private_motorcycles': 404749, 'public_motorcycles': 21.0, 'total_motorcycles': 404770, 'all_private': 10331882, 'all_public': 121476, 'total': 10453358, 'state_abbr': 'OH', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5a')}, {'state': 'Oklahoma', 'private_cars': 1381866, 'public_cars': 9936, 'total_cars': 1391802, 'private_buses': 908.0, 'public_buses': 1275, 'total_buses': 2183, 'private_trucks': 1983697, 'public_trucks': 10719, 'total_trucks': 1994416, 'private_motorcycles': 129404, 'public_motorcycles': 1.0, 'total_motorcycles': 129405, 'all_private': 3495875, 'all_public': 21931, 'total': 3517806, 'state_abbr': 'OK', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5b')}, {'state': 'Oregon', 'private_cars': 1387492, 'public_cars': 16025, 'total_cars': 1403517, 'private_buses': 4556.0, 'public_buses': 3063, 'total_buses': 7619, 'private_trucks': 1895949, 'public_trucks': 22627, 'total_trucks': 1918576, 'private_motorcycles': 88247, 'public_motorcycles': 0.0, 'total_motorcycles': 88247, 'all_private': 3376244, 'all_public': 41715, 'total': 3417959, 'state_abbr': 'OR', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5c')}, {'state': 'Pennsylvania', 'private_cars': 4664083, 'public_cars': 47036, 'total_cars': 4711119, 'private_buses': 52148.0, 'public_buses': 2618, 'total_buses': 54766, 'private_trucks': 5270712, 'public_trucks': 71845, 'total_trucks': 5342557, 'private_motorcycles': 395575, 'public_motorcycles': 740.0, 'total_motorcycles': 396315, 'all_private': 10382518, 'all_public': 122239, 'total': 10504757, 'state_abbr': 'PA', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5d')}, {'state': 'Rhode Island', 'private_cars': 447220, 'public_cars': 8301, 'total_cars': 455520, 'private_buses': 1754.0, 'public_buses': 364, 'total_buses': 2118, 'private_trucks': 368412, 'public_trucks': 6841, 'total_trucks': 375254, 'private_motorcycles': 31772, 'public_motorcycles': 98.0, 'total_motorcycles': 31870, 'all_private': 849158, 'all_public': 15604, 'total': 864762, 'state_abbr': 'RI', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5e')}, {'state': 'South Carolina', 'private_cars': 1711960, 'public_cars': 42122, 'total_cars': 1754081, 'private_buses': 5389.0, 'public_buses': 12469, 'total_buses': 17858, 'private_trucks': 2088878, 'public_trucks': 42127, 'total_trucks': 2131005, 'private_motorcycles': 114198, 'public_motorcycles': 468.0, 'total_motorcycles': 114666, 'all_private': 3920425, 'all_public': 97186, 'total': 4017611, 'state_abbr': 'SC', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa5f')}, {'state': 'South Dakota', 'private_cars': 317977, 'public_cars': 6183, 'total_cars': 324160, 'private_buses': 0.0, 'public_buses': 2664, 'total_buses': 2664, 'private_trucks': 599153, 'public_trucks': 17268, 'total_trucks': 616421, 'private_motorcycles': 88889, 'public_motorcycles': 571.0, 'total_motorcycles': 89460, 'all_private': 1006019, 'all_public': 26686, 'total': 1032705, 'state_abbr': 'SD', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa60')}, {'state': 'Tennessee', 'private_cars': 2236150, 'public_cars': 37362, 'total_cars': 2273513, 'private_buses': 2069.0, 'public_buses': 23960, 'total_buses': 26029, 'private_trucks': 2945617, 'public_trucks': 85779, 'total_trucks': 3031395, 'private_motorcycles': 162396, 'public_motorcycles': 2314.0, 'total_motorcycles': 164710, 'all_private': 5346232, 'all_public': 149415, 'total': 5495647, 'state_abbr': 'TN', 'year': '2014', '_id': ObjectId('5cafd42178a01b3a3c34fa61')}, {'state': 'Texas', 'private_cars': 7991684, 'public_cars': 148637, 'total_cars': 8140321, 'private_buses': 18931.0, 'public_buses': 82914, 'total_buses': 101845, 'private_trucks': 11901074, 'public_trucks': 288391, 'total_trucks': 12189465, 'private_motorcycles': 441291, 'public_motorcycles': 4104.0, 'total_motorcycles': 445395, 'all_private': 20

[{'state': 'Alabama', 'private_cars': 2262612, 'public_cars': 15650, 'total_cars': 2278262, 'private_buses': 5595, 'public_buses': 132, 'total_buses': 5727, 'private_trucks': 2975846, 'public_trucks': 25470, 'total_trucks': 3001316, 'private_motorcycles': 114178, 'public_motorcycles': 936, 'total_motorcycles': 115114, 'all_private': 5358231, 'all_public': 42188, 'total': 5400419, 'state_abbr': 'AL', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6a')}, {'state': 'Alaska', 'private_cars': 188848, 'public_cars': 4500, 'total_cars': 193348, 'private_buses': 3231, 'public_buses': 210, 'total_buses': 3441, 'private_trucks': 568936, 'public_trucks': 17444, 'total_trucks': 586380, 'private_motorcycles': 31945, 'public_motorcycles': 8, 'total_motorcycles': 31953, 'all_private': 792960, 'all_public': 22162, 'total': 815122, 'state_abbr': 'AK', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6b')}, {'state': 'Arizona', 'private_cars': 2311630, 'public_cars': 21104, 'total_cars': 2332734, 'private_buses': 13765, 'public_buses': 7284, 'total_buses': 21049, 'private_trucks': 3073975, 'public_trucks': 41751, 'total_trucks': 3115726, 'private_motorcycles': 161137, 'public_motorcycles': 1, 'total_motorcycles': 161138, 'all_private': 5560507, 'all_public': 70140, 'total': 5630647, 'state_abbr': 'AZ', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6c')}, {'state': 'Arkansas', 'private_cars': 931252, 'public_cars': 16537, 'total_cars': 947789, 'private_buses': 11112, 'public_buses': 701, 'total_buses': 11813, 'private_trucks': 1687935, 'public_trucks': 32873, 'total_trucks': 1720808, 'private_motorcycles': 91804, 'public_motorcycles': 0, 'total_motorcycles': 91804, 'all_private': 2722103, 'all_public': 50111, 'total': 2772214, 'state_abbr': 'AR', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6d')}, {'state': 'California', 'private_cars': 14232593, 'public_cars': 230976, 'total_cars': 14463569, 'private_buses': 34582, 'public_buses': 59438, 'total_buses': 94020, 'private_trucks': 13764734, 'public_trucks': 272806, 'total_trucks': 14037540, 'private_motorcycles': 814423, 'public_motorcycles': 14460, 'total_motorcycles': 828883, 'all_private': 28846332, 'all_public': 577680, 'total': 29424012, 'state_abbr': 'CA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6e')}, {'state': 'Colorado', 'private_cars': 1807666, 'public_cars': 14504, 'total_cars': 1822170, 'private_buses': 6044, 'public_buses': 6622, 'total_buses': 12666, 'private_trucks': 2946346, 'public_trucks': 32784, 'total_trucks': 2979130, 'private_motorcycles': 191206, 'public_motorcycles': 0, 'total_motorcycles': 191206, 'all_private': 4951262, 'all_public': 53910, 'total': 5005172, 'state_abbr': 'CO', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa6f')}, {'state': 'Connecticut', 'private_cars': 1384651, 'public_cars': 1216, 'total_cars': 1385867, 'private_buses': 12551, 'public_buses': 174, 'total_buses': 12725, 'private_trucks': 1351735, 'public_trucks': 4906, 'total_trucks': 1356641, 'private_motorcycles': 86511, 'public_motorcycles': 20, 'total_motorcycles': 86531, 'all_private': 2835448, 'all_public': 6316, 'total': 2841764, 'state_abbr': 'CT', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa70')}, {'state': 'Delaware', 'private_cars': 435350, 'public_cars': 2681, 'total_cars': 438031, 'private_buses': 3538, 'public_buses': 827, 'total_buses': 4365, 'private_trucks': 489557, 'public_trucks': 4184, 'total_trucks': 493741, 'private_motorcycles': 28179, 'public_motorcycles': 0, 'total_motorcycles': 28179, 'all_private': 956624, 'all_public': 7692, 'total': 964316, 'state_abbr': 'DE', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa71')}, {'state': 'Florida', 'private_cars': 7625692, 'public_cars': 109368, 'total_cars': 7735060, 'private_buses': 26156, 'public_buses': 33969, 'total_buses': 60125, 'private_trucks': 7608030, 'public_trucks': 129039, 'total_trucks': 7737069, 'private_motorcycles': 570172, 'public_motorcycles': 2582, 'total_motorcycles': 572754, 'all_private': 15830050, 'all_public': 274958, 'total': 16105008, 'state_abbr': 'FL', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa72')}, {'state': 'Georgia', 'private_cars': 3469663, 'public_cars': 53956, 'total_cars': 3523619, 'private_buses': 12363, 'public_buses': 30179, 'total_buses': 42542, 'private_trucks': 4294116, 'public_trucks': 76934, 'total_trucks': 4371050, 'private_motorcycles': 199552, 'public_motorcycles': 858, 'total_motorcycles': 200410, 'all_private': 7975694, 'all_public': 161927, 'total': 8137621, 'state_abbr': 'GA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa73')}, {'state': 'Hawaii', 'private_cars': 514962, 'public_cars': 7845, 'total_cars': 522807, 'private_buses': 2023, 'public_buses': 876, 'total_buses': 2899, 'private_trucks': 668057, 'public_trucks': 14752, 'total_trucks': 682809, 'private_motorcycles': 33431, 'public_motorcycles': 373, 'total_motorcycles': 33804, 'all_private': 1218473, 'all_public': 23846, 'total': 1242319, 'state_abbr': 'HI', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa74')}, {'state': 'Idaho', 'private_cars': 624560, 'public_cars': 1880, 'total_cars': 626440, 'private_buses': 2774, 'public_buses': 504, 'total_buses': 3278, 'private_trucks': 1150397, 'public_trucks': 8269, 'total_trucks': 1158666, 'private_motorcycles': 65604, 'public_motorcycles': 31, 'total_motorcycles': 65635, 'all_private': 1843335, 'all_public': 10684, 'total': 1854019, 'state_abbr': 'ID', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa75')}, {'state': 'Illinois', 'private_cars': 4734188, 'public_cars': 41226, 'total_cars': 4775414, 'private_buses': 34556, 'public_buses': 217, 'total_buses': 34773, 'private_trucks': 5380864, 'public_trucks': 57993, 'total_trucks': 5438857, 'private_motorcycles': 346210, 'public_motorcycles': 0, 'total_motorcycles': 346210, 'all_private': 10495818, 'all_public': 99436, 'total': 10595254, 'state_abbr': 'IL', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa76')}, {'state': 'Indiana', 'private_cars': 2333284, 'public_cars': 2516, 'total_cars': 2335800, 'private_buses': 8320, 'public_buses': 13485, 'total_buses': 21805, 'private_trucks': 3455001, 'public_trucks': 9138, 'total_trucks': 3464139, 'private_motorcycles': 223370, 'public_motorcycles': 0, 'total_motorcycles': 223370, 'all_private': 6019975, 'all_public': 25139, 'total': 6045114, 'state_abbr': 'IN', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa77')}, {'state': 'Iowa', 'private_cars': 1313761, 'public_cars': 12439, 'total_cars': 1326200, 'private_buses': 3847, 'public_buses': 5339, 'total_buses': 9186, 'private_trucks': 2089114, 'public_trucks': 22549, 'total_trucks': 2111663, 'private_motorcycles': 189519, 'public_motorcycles': 330, 'total_motorcycles': 189849, 'all_private': 3596241, 'all_public': 40657, 'total': 3636898, 'state_abbr': 'IA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa78')}, {'state': 'Kansas', 'private_cars': 979717, 'public_cars': 12300, 'total_cars': 992017, 'private_buses': 1639, 'public_buses': 2279, 'total_buses': 3918, 'private_trucks': 1520456, 'public_trucks': 22140, 'total_trucks': 1542596, 'private_motorcycles': 96325, 'public_motorcycles': 0, 'total_motorcycles': 96325, 'all_private': 2598137, 'all_public': 36719, 'total': 2634856, 'state_abbr': 'KS', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa79')}, {'state': 'Kentucky', 'private_cars': 1680771, 'public_cars': 33188, 'total_cars': 1713959, 'private_buses': 1292, 'public_buses': 9188, 'total_buses': 10480, 'private_trucks': 2267668, 'public_trucks': 48857, 'total_trucks': 2316525, 'private_motorcycles': 110938, 'public_motorcycles': 80, 'total_motorcycles': 111018, 'all_private': 4060669, 'all_public': 91313, 'total': 4151982, 'state_abbr': 'KY', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7a')}, {'state': 'Louisiana', 'private_cars': 1409821, 'public_cars': 28747, 'total_cars': 1438568, 'private_buses': 22185, 'public_buses': 6776, 'total_buses': 28961, 'private_trucks': 2269239, 'public_trucks': 50588, 'total_trucks': 2319827, 'private_motorcycles': 113599, 'public_motorcycles': 477, 'total_motorcycles': 114076, 'all_private': 3814844, 'all_public': 86588, 'total': 3901432, 'state_abbr': 'LA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7b')}, {'state': 'Maine', 'private_cars': 415262, 'public_cars': 4298, 'total_cars': 419560, 'private_buses': 1433, 'public_buses': 3022, 'total_buses': 4455, 'private_trucks': 617305, 'public_trucks': 8017, 'total_trucks': 625322, 'private_motorcycles': 54663, 'public_motorcycles': 1, 'total_motorcycles': 54664, 'all_private': 1088663, 'all_public': 15338, 'total': 1104001, 'state_abbr': 'ME', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7c')}, {'state': 'Maryland', 'private_cars': 1963565, 'public_cars': 30371, 'total_cars': 1993936, 'private_buses': 9136, 'public_buses': 4102, 'total_buses': 13238, 'private_trucks': 1961489, 'public_trucks': 40184, 'total_trucks': 2001673, 'private_motorcycles': 126235, 'public_motorcycles': 76, 'total_motorcycles': 126311, 'all_private': 4060425, 'all_public': 74733, 'total': 4135158, 'state_abbr': 'MD', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7d')}, {'state': 'Massachusetts', 'private_cars': 2349659, 'public_cars': 24564, 'total_cars': 2374223, 'private_buses': 10755, 'public_buses': 1029, 'total_buses': 11784, 'private_trucks': 2483352, 'public_trucks': 32413, 'total_trucks': 2515765, 'private_motorcycles': 167748, 'public_motorcycles': 81, 'total_motorcycles': 167829, 'all_private': 5011514, 'all_public': 58087, 'total': 5069601, 'state_abbr': 'MA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7e')}, {'state': 'Michigan', 'private_cars': 3350242, 'public_cars': 26440, 'total_cars': 3376682, 'private_buses': 3368, 'public_buses': 5281, 'total_buses': 8649, 'private_trucks': 4606397, 'public_trucks': 44915, 'total_trucks': 4651312, 'private_motorcycles': 257465, 'public_motorcycles': 0, 'total_motorcycles': 257465, 'all_private': 8217472, 'all_public': 76636, 'total': 8294108, 'state_abbr': 'MI', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa7f')}, {'state': 'Minnesota', 'private_cars': 2062252, 'public_cars': 17591, 'total_cars': 2079843, 'private_buses': 13653, 'public_buses': 5591, 'total_buses': 19244, 'private_trucks': 2903796, 'public_trucks': 29826, 'total_trucks': 2933622, 'private_motorcycles': 248560, 'public_motorcycles': 0, 'total_motorcycles': 248560, 'all_private': 5228261, 'all_public': 53008, 'total': 5281269, 'state_abbr': 'MN', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa80')}, {'state': 'Mississippi', 'private_cars': 844319, 'public_cars': 2854, 'total_cars': 847173, 'private_buses': 2003, 'public_buses': 6046, 'total_buses': 8049, 'private_trucks': 1177686, 'public_trucks': 7616, 'total_trucks': 1185302, 'private_motorcycles': 28329, 'public_motorcycles': 0, 'total_motorcycles': 28329, 'all_private': 2052337, 'all_public': 16516, 'total': 2068853, 'state_abbr': 'MS', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa81')}, {'state': 'Missouri', 'private_cars': 2253557, 'public_cars': 19541, 'total_cars': 2273098, 'private_buses': 9864, 'public_buses': 7021, 'total_buses': 16885, 'private_trucks': 3083265, 'public_trucks': 33026, 'total_trucks': 3116291, 'private_motorcycles': 217731, 'public_motorcycles': 0, 'total_motorcycles': 217731, 'all_private': 5564417, 'all_public': 59588, 'total': 5624005, 'state_abbr': 'MO', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa82')}, {'state': 'Montana', 'private_cars': 435151, 'public_cars': 779, 'total_cars': 435930, 'private_buses': 4425, 'public_buses': 159, 'total_buses': 4584, 'private_trucks': 1000837, 'public_trucks': 6446, 'total_trucks': 1007283, 'private_motorcycles': 197426, 'public_motorcycles': 4, 'total_motorcycles': 197430, 'all_private': 1637839, 'all_public': 7388, 'total': 1645227, 'state_abbr': 'MT', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa83')}, {'state': 'Nebraska', 'private_cars': 717111, 'public_cars': 15745, 'total_cars': 732856, 'private_buses': 3875, 'public_buses': 70, 'total_buses': 3945, 'private_trucks': 1160821, 'public_trucks': 27739, 'total_trucks': 1188560, 'private_motorcycles': 55912, 'public_motorcycles': 23, 'total_motorcycles': 55935, 'all_private': 1937719, 'all_public': 43577, 'total': 1981296, 'state_abbr': 'NE', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa84')}, {'state': 'Nevada', 'private_cars': 1009483, 'public_cars': 8051, 'total_cars': 1017534, 'private_buses': 482, 'public_buses': 2646, 'total_buses': 3128, 'private_trucks': 1206023, 'public_trucks': 14845, 'total_trucks': 1220868, 'private_motorcycles': 74521, 'public_motorcycles': 5, 'total_motorcycles': 74526, 'all_private': 2290509, 'all_public': 25547, 'total': 2316056, 'state_abbr': 'NV', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa85')}, {'state': 'New Hampshire', 'private_cars': 530943, 'public_cars': 4245, 'total_cars': 535188, 'private_buses': 590, 'public_buses': 2232, 'total_buses': 2822, 'private_trucks': 677298, 'public_trucks': 6838, 'total_trucks': 684136, 'private_motorcycles': 73991, 'public_motorcycles': 0, 'total_motorcycles': 73991, 'all_private': 1282822, 'all_public': 13315, 'total': 1296137, 'state_abbr': 'NH', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa86')}, {'state': 'New Jersey', 'private_cars': 2877891, 'public_cars': 40712, 'total_cars': 2918603, 'private_buses': 22070, 'public_buses': 2290, 'total_buses': 24360, 'private_trucks': 2794282, 'public_trucks': 48868, 'total_trucks': 2843150, 'private_motorcycles': 152472, 'public_motorcycles': 0, 'total_motorcycles': 152472, 'all_private': 5846715, 'all_public': 91870, 'total': 5938585, 'state_abbr': 'NJ', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa87')}, {'state': 'New Mexico', 'private_cars': 659911, 'public_cars': 8036, 'total_cars': 667947, 'private_buses': 4977, 'public_buses': 1262, 'total_buses': 6239, 'private_trucks': 1064167, 'public_trucks': 21844, 'total_trucks': 1086011, 'private_motorcycles': 63248, 'public_motorcycles': 0, 'total_motorcycles': 63248, 'all_private': 1792303, 'all_public': 31142, 'total': 1823445, 'state_abbr': 'NM', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa88')}, {'state': 'New York', 'private_cars': 4823532, 'public_cars': 44989, 'total_cars': 4868521, 'private_buses': 7739, 'public_buses': 22881, 'total_buses': 30620, 'private_trucks': 5321177, 'public_trucks': 63589, 'total_trucks': 5384766, 'private_motorcycles': 354856, 'public_motorcycles': 2, 'total_motorcycles': 354858, 'all_private': 10507304, 'all_public': 131461, 'total': 10638765, 'state_abbr': 'NY', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa89')}, {'state': 'North Carolina', 'private_cars': 3391383, 'public_cars': 47768, 'total_cars': 3439151, 'private_buses': 11526, 'public_buses': 20244, 'total_buses': 31770, 'private_trucks': 4201219, 'public_trucks': 67911, 'total_trucks': 4269130, 'private_motorcycles': 188659, 'public_motorcycles': 263, 'total_motorcycles': 188922, 'all_private': 7792787, 'all_public': 136186, 'total': 7928973, 'state_abbr': 'NC', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8a')}, {'state': 'North Dakota', 'private_cars': 243032, 'public_cars': 4372, 'total_cars': 247404, 'private_buses': 951, 'public_buses': 1868, 'total_buses': 2819, 'private_trucks': 588530, 'public_trucks': 13042, 'total_trucks': 601572, 'private_motorcycles': 38994, 'public_motorcycles': 14, 'total_motorcycles': 39008, 'all_private': 871507, 'all_public': 19296, 'total': 890803, 'state_abbr': 'ND', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8b')}, {'state': 'Ohio', 'private_cars': 4691057, 'public_cars': 47743, 'total_cars': 4738800, 'private_buses': 30235, 'public_buses': 6711, 'total_buses': 36946, 'private_trucks': 5312365, 'public_trucks': 64256, 'total_trucks': 5376621, 'private_motorcycles': 404934, 'public_motorcycles': 22, 'total_motorcycles': 404956, 'all_private': 10438591, 'all_public': 118732, 'total': 10557323, 'state_abbr': 'OH', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8c')}, {'state': 'Oklahoma', 'private_cars': 1149328, 'public_cars': 7278, 'total_cars': 1156606, 'private_buses': 1930, 'public_buses': 1275, 'total_buses': 3205, 'private_trucks': 1684404, 'public_trucks': 15204, 'total_trucks': 1699608, 'private_motorcycles': 129092, 'public_motorcycles': 1, 'total_motorcycles': 129093, 'all_private': 2964754, 'all_public': 23758, 'total': 2988512, 'state_abbr': 'OK', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8d')}, {'state': 'Oregon', 'private_cars': 1408029, 'public_cars': 24876, 'total_cars': 1432905, 'private_buses': 7571, 'public_buses': 8433, 'total_buses': 16004, 'private_trucks': 1988237, 'public_trucks': 42028, 'total_trucks': 2030265, 'private_motorcycles': 127557, 'public_motorcycles': 751, 'total_motorcycles': 128308, 'all_private': 3531394, 'all_public': 76088, 'total': 3607482, 'state_abbr': 'OR', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8e')}, {'state': 'Pennsylvania', 'private_cars': 4630273, 'public_cars': 50225, 'total_cars': 4680498, 'private_buses': 52502, 'public_buses': 2615, 'total_buses': 55117, 'private_trucks': 5400602, 'public_trucks': 69087, 'total_trucks': 5469689, 'private_motorcycles': 392653, 'public_motorcycles': 737, 'total_motorcycles': 393390, 'all_private': 10476030, 'all_public': 122664, 'total': 10598694, 'state_abbr': 'PA', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa8f')}, {'state': 'Rhode Island', 'private_cars': 440005, 'public_cars': 7351, 'total_cars': 447356, 'private_buses': 1803, 'public_buses': 374, 'total_buses': 2177, 'private_trucks': 385887, 'public_trucks': 7926, 'total_trucks': 393813, 'private_motorcycles': 31651, 'public_motorcycles': 100, 'total_motorcycles': 31751, 'all_private': 859346, 'all_public': 15751, 'total': 875097, 'state_abbr': 'RI', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa90')}, {'state': 'South Carolina', 'private_cars': 1727108, 'public_cars': 56896, 'total_cars': 1784004, 'private_buses': 5324, 'public_buses': 12366, 'total_buses': 17690, 'private_trucks': 2168206, 'public_trucks': 76510, 'total_trucks': 2244716, 'private_motorcycles': 115769, 'public_motorcycles': 472, 'total_motorcycles': 116241, 'all_private': 4016407, 'all_public': 146244, 'total': 4162651, 'state_abbr': 'SC', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa91')}, {'state': 'South Dakota', 'private_cars': 321188, 'public_cars': 7609, 'total_cars': 328797, 'private_buses': 232, 'public_buses': 2608, 'total_buses': 2840, 'private_trucks': 637389, 'public_trucks': 17344, 'total_trucks': 654733, 'private_motorcycles': 95278, 'public_motorcycles': 641, 'total_motorcycles': 95919, 'all_private': 1054087, 'all_public': 28202, 'total': 1082289, 'state_abbr': 'SD', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa92')}, {'state': 'Tennessee', 'private_cars': 2268376, 'public_cars': 49948, 'total_cars': 2318324, 'private_buses': 2160, 'public_buses': 24048, 'total_buses': 26208, 'private_trucks': 3027665, 'public_trucks': 73666, 'total_trucks': 3101331, 'private_motorcycles': 163911, 'public_motorcycles': 2349, 'total_motorcycles': 166260, 'all_private': 5462112, 'all_public': 150011, 'total': 5612123, 'state_abbr': 'TN', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa93')}, {'state': 'Texas', 'private_cars': 8356594, 'public_cars': 94445, 'total_cars': 8451039, 'private_buses': 19339, 'public_buses': 47641, 'total_buses': 66980, 'private_trucks': 12787563, 'public_trucks': 172110, 'total_trucks': 12959673, 'private_motorcycles': 386220, 'public_motorcycles': 929, 'total_motorcycles': 387149, 'all_private': 21549716, 'all_public': 315125, 'total': 21864841, 'state_abbr': 'TX', 'year': '2015', '_id': ObjectId('5cafd42278a01b3a3c34fa94')}, {'state': 'Utah', 'private_cars':

[{'state': 'Alabama', 'private_cars': 2239705, 'public_cars': 44738, 'total_cars': 2284443, 'private_buses': 6107, 'public_buses': 131, 'total_buses': 6238, 'private_trucks': 3002931, 'public_trucks': 64986, 'total_trucks': 3067917, 'private_motorcycles': 108767, 'public_motorcycles': 936, 'total_motorcycles': 109703, 'all_private': 5357510, 'all_public': 110791, 'total': 5468301, 'state_abbr': 'AL', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fa9c')}, {'state': 'Alaska', 'private_cars': 178860, 'public_cars': 4399, 'total_cars': 183259, 'private_buses': 7529, 'public_buses': 590, 'total_buses': 8119, 'private_trucks': 553730, 'public_trucks': 17557, 'total_trucks': 571287, 'private_motorcycles': 31942, 'public_motorcycles': 7, 'total_motorcycles': 31949, 'all_private': 772061, 'all_public': 22553, 'total': 794614, 'state_abbr': 'AK', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fa9d')}, {'state': 'Arizona', 'private_cars': 2357093, 'public_cars': 20869, 'total_cars': 2377962, 'private_buses': 1475, 'public_buses': 7541, 'total_buses': 9016, 'private_trucks': 3190517, 'public_trucks': 42813, 'total_trucks': 3233330, 'private_motorcycles': 166582, 'public_motorcycles': 1, 'total_motorcycles': 166583, 'all_private': 5715667, 'all_public': 71224, 'total': 5786891, 'state_abbr': 'AZ', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fa9e')}, {'state': 'Arkansas', 'private_cars': 929740, 'public_cars': 12864, 'total_cars': 942604, 'private_buses': 11209, 'public_buses': 722, 'total_buses': 11931, 'private_trucks': 1735726, 'public_trucks': 27039, 'total_trucks': 1762765, 'private_motorcycles': 90838, 'public_motorcycles': 0, 'total_motorcycles': 90838, 'all_private': 2767513, 'all_public': 40625, 'total': 2808138, 'state_abbr': 'AR', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fa9f')}, {'state': 'California', 'private_cars': 14526096, 'public_cars': 242296, 'total_cars': 14768392, 'private_buses': 34994, 'public_buses': 63628, 'total_buses': 98622, 'private_trucks': 14223347, 'public_trucks': 288566, 'total_trucks': 14511913, 'private_motorcycles': 827634, 'public_motorcycles': 14472, 'total_motorcycles': 842106, 'all_private': 29612071, 'all_public': 608962, 'total': 30221033, 'state_abbr': 'CA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa0')}, {'state': 'Colorado', 'private_cars': 1790622, 'public_cars': 17155, 'total_cars': 1807777, 'private_buses': 5935, 'public_buses': 6836, 'total_buses': 12771, 'private_trucks': 3065910, 'public_trucks': 39291, 'total_trucks': 3105201, 'private_motorcycles': 190531, 'public_motorcycles': 61, 'total_motorcycles': 190592, 'all_private': 5052998, 'all_public': 63343, 'total': 5116341, 'state_abbr': 'CO', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa1')}, {'state': 'Connecticut', 'private_cars': 1351171, 'public_cars': 1210, 'total_cars': 1352381, 'private_buses': 12551, 'public_buses': 36, 'total_buses': 12587, 'private_trucks': 1385215, 'public_trucks': 5128, 'total_trucks': 1390343, 'private_motorcycles': 86511, 'public_motorcycles': 20, 'total_motorcycles': 86531, 'all_private': 2835448, 'all_public': 6394, 'total': 2841842, 'state_abbr': 'CT', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa2')}, {'state': 'Delaware', 'private_cars': 445444, 'public_cars': 1563, 'total_cars': 447007, 'private_buses': 3863, 'public_buses': 425, 'total_buses': 4288, 'private_trucks': 521373, 'public_trucks': 3014, 'total_trucks': 524387, 'private_motorcycles': 28158, 'public_motorcycles': 0, 'total_motorcycles': 28158, 'all_private': 998838, 'all_public': 5002, 'total': 1003840, 'state_abbr': 'DE', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa3')}, {'state': 'Florida', 'private_cars': 7745321, 'public_cars': 109929, 'total_cars': 7855250, 'private_buses': 25356, 'public_buses': 34452, 'total_buses': 59808, 'private_trucks': 7968659, 'public_trucks': 133952, 'total_trucks': 8102611, 'private_motorcycles': 580002, 'public_motorcycles': 2646, 'total_motorcycles': 582648, 'all_private': 16319338, 'all_public': 280979, 'total': 16600317, 'state_abbr': 'FL', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa4')}, {'state': 'Georgia', 'private_cars': 3485821, 'public_cars': 52359, 'total_cars': 3538180, 'private_buses': 12101, 'public_buses': 25386, 'total_buses': 37487, 'private_trucks': 4385246, 'public_trucks': 76475, 'total_trucks': 4461721, 'private_motorcycles': 201508, 'public_motorcycles': 883, 'total_motorcycles': 202391, 'all_private': 8084676, 'all_public': 155103, 'total': 8239779, 'state_abbr': 'GA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa5')}, {'state': 'Hawaii', 'private_cars': 508549, 'public_cars': 7995, 'total_cars': 516544, 'private_buses': 1774, 'public_buses': 1295, 'total_buses': 3069, 'private_trucks': 665951, 'public_trucks': 15018, 'total_trucks': 680969, 'private_motorcycles': 30768, 'public_motorcycles': 378, 'total_motorcycles': 31146, 'all_private': 1207042, 'all_public': 24686, 'total': 1231728, 'state_abbr': 'HI', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa6')}, {'state': 'Idaho', 'private_cars': 605599, 'public_cars': 2303, 'total_cars': 607902, 'private_buses': 3184, 'public_buses': 693, 'total_buses': 3877, 'private_trucks': 1154988, 'public_trucks': 9539, 'total_trucks': 1164527, 'private_motorcycles': 65894, 'public_motorcycles': 45, 'total_motorcycles': 65939, 'all_private': 1829665, 'all_public': 12580, 'total': 1842245, 'state_abbr': 'ID', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa7')}, {'state': 'Illinois', 'private_cars': 4484546, 'public_cars': 40163, 'total_cars': 4524709, 'private_buses': 34751, 'public_buses': 185, 'total_buses': 34936, 'private_trucks': 5342899, 'public_trucks': 59831, 'total_trucks': 5402730, 'private_motorcycles': 314807, 'public_motorcycles': 0, 'total_motorcycles': 314807, 'all_private': 10177003, 'all_public': 100179, 'total': 10277182, 'state_abbr': 'IL', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa8')}, {'state': 'Indiana', 'private_cars': 2327229, 'public_cars': 2943, 'total_cars': 2330172, 'private_buses': 7228, 'public_buses': 13499, 'total_buses': 20727, 'private_trucks': 3556047, 'public_trucks': 9981, 'total_trucks': 3566028, 'private_motorcycles': 223566, 'public_motorcycles': 37, 'total_motorcycles': 223603, 'all_private': 6114070, 'all_public': 26460, 'total': 6140530, 'state_abbr': 'IN', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faa9')}, {'state': 'Iowa', 'private_cars': 1291027, 'public_cars': 12104, 'total_cars': 1303131, 'private_buses': 3835, 'public_buses': 5339, 'total_buses': 9174, 'private_trucks': 2148625, 'public_trucks': 22926, 'total_trucks': 2171551, 'private_motorcycles': 192104, 'public_motorcycles': 330, 'total_motorcycles': 192434, 'all_private': 3635591, 'all_public': 40699, 'total': 3676290, 'state_abbr': 'IA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faaa')}, {'state': 'Kansas', 'private_cars': 976261, 'public_cars': 4098, 'total_cars': 980359, 'private_buses': 3295, 'public_buses': 2280, 'total_buses': 5575, 'private_trucks': 1557827, 'public_trucks': 9728, 'total_trucks': 1567555, 'private_motorcycles': 96205, 'public_motorcycles': 42, 'total_motorcycles': 96247, 'all_private': 2633588, 'all_public': 16148, 'total': 2649736, 'state_abbr': 'KS', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faab')}, {'state': 'Kentucky', 'private_cars': 1680846, 'public_cars': 32744, 'total_cars': 1713590, 'private_buses': 1358, 'public_buses': 9201, 'total_buses': 10559, 'private_trucks': 2344262, 'public_trucks': 49729, 'total_trucks': 2393991, 'private_motorcycles': 106569, 'public_motorcycles': 79, 'total_motorcycles': 106648, 'all_private': 4133035, 'all_public': 91753, 'total': 4224788, 'state_abbr': 'KY', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faac')}, {'state': 'Louisiana', 'private_cars': 1395694, 'public_cars': 29655, 'total_cars': 1425349, 'private_buses': 22185, 'public_buses': 7003, 'total_buses': 29188, 'private_trucks': 2283366, 'public_trucks': 53460, 'total_trucks': 2336826, 'private_motorcycles': 113599, 'public_motorcycles': 0, 'total_motorcycles': 113599, 'all_private': 3814844, 'all_public': 90118, 'total': 3904962, 'state_abbr': 'LA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faad')}, {'state': 'Maine', 'private_cars': 405063, 'public_cars': 4166, 'total_cars': 409229, 'private_buses': 1328, 'public_buses': 3021, 'total_buses': 4349, 'private_trucks': 633559, 'public_trucks': 8163, 'total_trucks': 641722, 'private_motorcycles': 52373, 'public_motorcycles': 1, 'total_motorcycles': 52374, 'all_private': 1092323, 'all_public': 15351, 'total': 1107674, 'state_abbr': 'ME', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faae')}, {'state': 'Maryland', 'private_cars': 1946027, 'public_cars': 29994, 'total_cars': 1976021, 'private_buses': 15047, 'public_buses': 7754, 'total_buses': 22801, 'private_trucks': 2015106, 'public_trucks': 41009, 'total_trucks': 2056115, 'private_motorcycles': 123860, 'public_motorcycles': 76, 'total_motorcycles': 123936, 'all_private': 4100040, 'all_public': 78833, 'total': 4178873, 'state_abbr': 'MD', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faaf')}, {'state': 'Massachusetts', 'private_cars': 2281877, 'public_cars': 23594, 'total_cars': 2305471, 'private_buses': 10755, 'public_buses': 1024, 'total_buses': 11779, 'private_trucks': 2551134, 'public_trucks': 33346, 'total_trucks': 2584480, 'private_motorcycles': 167748, 'public_motorcycles': 81, 'total_motorcycles': 167829, 'all_private': 5011514, 'all_public': 58045, 'total': 5069559, 'state_abbr': 'MA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab0')}, {'state': 'Michigan', 'private_cars': 3223117, 'public_cars': 25242, 'total_cars': 3248359, 'private_buses': 3368, 'public_buses': 5288, 'total_buses': 8656, 'private_trucks': 4772452, 'public_trucks': 46777, 'total_trucks': 4819229, 'private_motorcycles': 256651, 'public_motorcycles': 0, 'total_motorcycles': 256651, 'all_private': 8255588, 'all_public': 77307, 'total': 8332895, 'state_abbr': 'MI', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab1')}, {'state': 'Minnesota', 'private_cars': 2064532, 'public_cars': 17191, 'total_cars': 2081723, 'private_buses': 13588, 'public_buses': 5591, 'total_buses': 19179, 'private_trucks': 2997572, 'public_trucks': 30466, 'total_trucks': 3028038, 'private_motorcycles': 229377, 'public_motorcycles': 0, 'total_motorcycles': 229377, 'all_private': 5305069, 'all_public': 53248, 'total': 5358317, 'state_abbr': 'MN', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab2')}, {'state': 'Mississippi', 'private_cars': 837962, 'public_cars': 2775, 'total_cars': 840737, 'private_buses': 2069, 'public_buses': 6019, 'total_buses': 8088, 'private_trucks': 1182517, 'public_trucks': 7641, 'total_trucks': 1190158, 'private_motorcycles': 28239, 'public_motorcycles': 0, 'total_motorcycles': 28239, 'all_private': 2050787, 'all_public': 16435, 'total': 2067222, 'state_abbr': 'MS', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab3')}, {'state': 'Missouri', 'private_cars': 2228930, 'public_cars': 18984, 'total_cars': 2247914, 'private_buses': 27446, 'public_buses': 123, 'total_buses': 27569, 'private_trucks': 3221609, 'public_trucks': 33853, 'total_trucks': 3255462, 'private_motorcycles': 153580, 'public_motorcycles': 0, 'total_motorcycles': 153580, 'all_private': 5631565, 'all_public': 52960, 'total': 5684525, 'state_abbr': 'MO', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab4')}, {'state': 'Montana', 'private_cars': 440423, 'public_cars': 778, 'total_cars': 441201, 'private_buses': 4491, 'public_buses': 143, 'total_buses': 4634, 'private_trucks': 1051940, 'public_trucks': 6662, 'total_trucks': 1058602, 'private_motorcycles': 290291, 'public_motorcycles': 4, 'total_motorcycles': 290295, 'all_private': 1787145, 'all_public': 7587, 'total': 1794732, 'state_abbr': 'MT', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab5')}, {'state': 'Nebraska', 'private_cars': 685275, 'public_cars': 15002, 'total_cars': 700277, 'private_buses': 13414, 'public_buses': 38, 'total_buses': 13452, 'private_trucks': 1155178, 'public_trucks': 27499, 'total_trucks': 1182677, 'private_motorcycles': 55340, 'public_motorcycles': 20, 'total_motorcycles': 55360, 'all_private': 1909207, 'all_public': 42559, 'total': 1951766, 'state_abbr': 'NE', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab6')}, {'state': 'Nevada', 'private_cars': 1039332, 'public_cars': 8030, 'total_cars': 1047362, 'private_buses': 482, 'public_buses': 2646, 'total_buses': 3128, 'private_trucks': 1258326, 'public_trucks': 15281, 'total_trucks': 1273607, 'private_motorcycles': 74557, 'public_motorcycles': 5, 'total_motorcycles': 74562, 'all_private': 2372697, 'all_public': 25962, 'total': 2398659, 'state_abbr': 'NV', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab7')}, {'state': 'New Hampshire', 'private_cars': 525365, 'public_cars': 4126, 'total_cars': 529491, 'private_buses': 566, 'public_buses': 2232, 'total_buses': 2798, 'private_trucks': 705160, 'public_trucks': 7015, 'total_trucks': 712175, 'private_motorcycles': 78218, 'public_motorcycles': 0, 'total_motorcycles': 78218, 'all_private': 1309309, 'all_public': 13373, 'total': 1322682, 'state_abbr': 'NH', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab8')}, {'state': 'New Jersey', 'private_cars': 2823062, 'public_cars': 24819, 'total_cars': 2847881, 'private_buses': 22769, 'public_buses': 2280, 'total_buses': 25049, 'private_trucks': 2882053, 'public_trucks': 34913, 'total_trucks': 2916966, 'private_motorcycles': 151101, 'public_motorcycles': 0, 'total_motorcycles': 151101, 'all_private': 5878985, 'all_public': 62012, 'total': 5940997, 'state_abbr': 'NJ', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fab9')}, {'state': 'New Mexico', 'private_cars': 653178, 'public_cars': 8019, 'total_cars': 661197, 'private_buses': 6076, 'public_buses': 207, 'total_buses': 6283, 'private_trucks': 1072069, 'public_trucks': 22535, 'total_trucks': 1094604, 'private_motorcycles': 61877, 'public_motorcycles': 0, 'total_motorcycles': 61877, 'all_private': 1793200, 'all_public': 30761, 'total': 1823961, 'state_abbr': 'NM', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34faba')}, {'state': 'New York', 'private_cars': 4868791, 'public_cars': 22125, 'total_cars': 4890916, 'private_buses': 73771, 'public_buses': 7009, 'total_buses': 80780, 'private_trucks': 5716772, 'public_trucks': 41153, 'total_trucks': 5757925, 'private_motorcycles': 392763, 'public_motorcycles': 8, 'total_motorcycles': 392771, 'all_private': 11052097, 'all_public': 70295, 'total': 11122392, 'state_abbr': 'NY', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fabb')}, {'state': 'North Carolina', 'private_cars': 3498169, 'public_cars': 48194, 'total_cars': 3546363, 'private_buses': 12065, 'public_buses': 20460, 'total_buses': 32525, 'private_trucks': 4425918, 'public_trucks': 70219, 'total_trucks': 4496137, 'private_motorcycles': 195336, 'public_motorcycles': 282, 'total_motorcycles': 195618, 'all_private': 8131488, 'all_public': 139155, 'total': 8270643, 'state_abbr': 'NC', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fabc')}, {'state': 'North Dakota', 'private_cars': 238964, 'public_cars': 4374, 'total_cars': 243338, 'private_buses': 970, 'public_buses': 1865, 'total_buses': 2835, 'private_trucks': 596328, 'public_trucks': 13453, 'total_trucks': 609781, 'private_motorcycles': 38985, 'public_motorcycles': 15, 'total_motorcycles': 39000, 'all_private': 875247, 'all_public': 19707, 'total': 894954, 'state_abbr': 'ND', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fabd')}, {'state': 'Ohio', 'private_cars': 4648574, 'public_cars': 45373, 'total_cars': 4693947, 'private_buses': 34203, 'public_buses': 6641, 'total_buses': 40844, 'private_trucks': 5478824, 'public_trucks': 64328, 'total_trucks': 5543152, 'private_motorcycles': 408088, 'public_motorcycles': 26, 'total_motorcycles': 408114, 'all_private': 10569689, 'all_public': 116368, 'total': 10686057, 'state_abbr': 'OH', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fabe')}, {'state': 'Oklahoma', 'private_cars': 1371425, 'public_cars': 7797, 'total_cars': 1379222, 'private_buses': 1880, 'public_buses': 1291, 'total_buses': 3171, 'private_trucks': 2201925, 'public_trucks': 17150, 'total_trucks': 2219075, 'private_motorcycles': 135936, 'public_motorcycles': 1, 'total_motorcycles': 135937, 'all_private': 3711166, 'all_public': 26239, 'total': 3737405, 'state_abbr': 'OK', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fabf')}, {'state': 'Oregon', 'private_cars': 1458348, 'public_cars': 25228, 'total_cars': 1483576, 'private_buses': 8209, 'public_buses': 8860, 'total_buses': 17069, 'private_trucks': 2130200, 'public_trucks': 44623, 'total_trucks': 2174823, 'private_motorcycles': 135464, 'public_motorcycles': 774, 'total_motorcycles': 136238, 'all_private': 3732221, 'all_public': 79485, 'total': 3811706, 'state_abbr': 'OR', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac0')}, {'state': 'Pennsylvania', 'private_cars': 4590646, 'public_cars': 49825, 'total_cars': 4640471, 'private_buses': 53160, 'public_buses': 2688, 'total_buses': 55848, 'private_trucks': 5587285, 'public_trucks': 72181, 'total_trucks': 5659466, 'private_motorcycles': 392252, 'public_motorcycles': 785, 'total_motorcycles': 393037, 'all_private': 10623343, 'all_public': 125479, 'total': 10748822, 'state_abbr': 'PA', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac1')}, {'state': 'Rhode Island', 'private_cars': 428967, 'public_cars': 7280, 'total_cars': 436247, 'private_buses': 1879, 'public_buses': 406, 'total_buses': 2285, 'private_trucks': 398255, 'public_trucks': 8304, 'total_trucks': 406559, 'private_motorcycles': 31034, 'public_motorcycles': 103, 'total_motorcycles': 31137, 'all_private': 860135, 'all_public': 16093, 'total': 876228, 'state_abbr': 'RI', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac2')}, {'state': 'South Carolina', 'private_cars': 1754908, 'public_cars': 85449, 'total_cars': 1840357, 'private_buses': 5408, 'public_buses': 12305, 'total_buses': 17713, 'private_trucks': 2234416, 'public_trucks': 113832, 'total_trucks': 2348248, 'private_motorcycles': 117633, 'public_motorcycles': 472, 'total_motorcycles': 118105, 'all_private': 4112365, 'all_public': 212058, 'total': 4324423, 'state_abbr': 'SC', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac3')}, {'state': 'South Dakota', 'private_cars': 358446, 'public_cars': 6130, 'total_cars': 364576, 'private_buses': 0, 'public_buses': 2339, 'total_buses': 2339, 'private_trucks': 749715, 'public_trucks': 14987, 'total_trucks': 764702, 'private_motorcycles': 114143, 'public_motorcycles': 599, 'total_motorcycles': 114742, 'all_private': 1222304, 'all_public': 24055, 'total': 1246359, 'state_abbr': 'SD', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac4')}, {'state': 'Tennessee', 'private_cars': 2295987, 'public_cars': 51819, 'total_cars': 2347806, 'private_buses': 2892, 'public_buses': 25150, 'total_buses': 28042, 'private_trucks': 3088978, 'public_trucks': 77136, 'total_trucks': 3166114, 'private_motorcycles': 165507, 'public_motorcycles': 2454, 'total_motorcycles': 167961, 'all_private': 5553364, 'all_public': 156559, 'total': 5709923, 'state_abbr': 'TN', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac5')}, {'state': 'Texas', 'private_cars': 8193715, 'public_cars': 93539, 'total_cars': 8287254, 'private_buses': 18647, 'public_buses': 48050, 'total_buses': 66697, 'private_trucks': 12861711, 'public_trucks': 175585, 'total_trucks': 13037296, 'private_motorcycles': 374018, 'public_motorcycles': 901, 'total_motorcycles': 374919, 'all_private': 21448091, 'all_public': 318075, 'total': 21766166, 'state_abbr': 'TX', 'year': '2016', '_id': ObjectId('5cafd42278a01b3a3c34fac6')}, {'state': 'Utah', 'private_cars

[{'state': 'Alabama', 'private_cars': 2021395, 'public_cars': 44068, 'total_cars': 2065463, 'private_buses': 5550, 'public_buses': 132, 'total_buses': 5682, 'private_trucks': 2806624, 'public_trucks': 66119, 'total_trucks': 2872743, 'private_motorcycles': 111247, 'public_motorcycles': 938, 'total_motorcycles': 112185, 'all_private': 4944816, 'all_public': 111257, 'total': 5056073, 'state_abbr': 'AL', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34face')}, {'state': 'Alaska', 'private_cars': 169412, 'public_cars': 4075, 'total_cars': 173487, 'private_buses': 7496, 'public_buses': 584, 'total_buses': 8080, 'private_trucks': 573399, 'public_trucks': 17680, 'total_trucks': 591079, 'private_motorcycles': 31852, 'public_motorcycles': 7, 'total_motorcycles': 31859, 'all_private': 782159, 'all_public': 22346, 'total': 804505, 'state_abbr': 'AK', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34facf')}, {'state': 'Arizona', 'private_cars': 2371199, 'public_cars': 20425, 'total_cars': 2391624, 'private_buses': 1508, 'public_buses': 7543, 'total_buses': 9051, 'private_trucks': 3356363, 'public_trucks': 43341, 'total_trucks': 3399704, 'private_motorcycles': 164053, 'public_motorcycles': 2, 'total_motorcycles': 164055, 'all_private': 5893123, 'all_public': 71311, 'total': 5964434, 'state_abbr': 'AZ', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad0')}, {'state': 'Arkansas', 'private_cars': 914265, 'public_cars': 12524, 'total_cars': 926789, 'private_buses': 11229, 'public_buses': 712, 'total_buses': 11941, 'private_trucks': 1778174, 'public_trucks': 27336, 'total_trucks': 1805510, 'private_motorcycles': 89457, 'public_motorcycles': 0, 'total_motorcycles': 89457, 'all_private': 2793125, 'all_public': 40572, 'total': 2833697, 'state_abbr': 'AR', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad1')}, {'state': 'California', 'private_cars': 14615499, 'public_cars': 245468, 'total_cars': 14860967, 'private_buses': 35253, 'public_buses': 64664, 'total_buses': 99917, 'private_trucks': 14693888, 'public_trucks': 297826, 'total_trucks': 14991714, 'private_motorcycles': 828083, 'public_motorcycles': 14460, 'total_motorcycles': 842543, 'all_private': 30172723, 'all_public': 622418, 'total': 30795141, 'state_abbr': 'CA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad2')}, {'state': 'Colorado', 'private_cars': 1768221, 'public_cars': 16837, 'total_cars': 1785058, 'private_buses': 5998, 'public_buses': 7307, 'total_buses': 13305, 'private_trucks': 3231050, 'public_trucks': 40545, 'total_trucks': 3271595, 'private_motorcycles': 190002, 'public_motorcycles': 0, 'total_motorcycles': 190002, 'all_private': 5195271, 'all_public': 64689, 'total': 5259960, 'state_abbr': 'CO', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad3')}, {'state': 'Connecticut', 'private_cars': 1301153, 'public_cars': 1186, 'total_cars': 1302339, 'private_buses': 11342, 'public_buses': 36, 'total_buses': 11378, 'private_trucks': 1417371, 'public_trucks': 5131, 'total_trucks': 1422502, 'private_motorcycles': 90111, 'public_motorcycles': 20, 'total_motorcycles': 90131, 'all_private': 2819977, 'all_public': 6373, 'total': 2826350, 'state_abbr': 'CT', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad4')}, {'state': 'Delaware', 'private_cars': 417700, 'public_cars': 1499, 'total_cars': 419199, 'private_buses': 3335, 'public_buses': 428, 'total_buses': 3763, 'private_trucks': 516931, 'public_trucks': 3030, 'total_trucks': 519961, 'private_motorcycles': 27810, 'public_motorcycles': 0, 'total_motorcycles': 27810, 'all_private': 965776, 'all_public': 4957, 'total': 970733, 'state_abbr': 'DE', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad5')}, {'state': 'Florida', 'private_cars': 7670861, 'public_cars': 107632, 'total_cars': 7778493, 'private_buses': 25004, 'public_buses': 34592, 'total_buses': 59596, 'private_trucks': 8396619, 'public_trucks': 138294, 'total_trucks': 8534913, 'private_motorcycles': 583685, 'public_motorcycles': 2582, 'total_motorcycles': 586267, 'all_private': 16676169, 'all_public': 283100, 'total': 16959269, 'state_abbr': 'FL', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad6')}, {'state': 'Georgia', 'private_cars': 3481721, 'public_cars': 54334, 'total_cars': 3536055, 'private_buses': 12164, 'public_buses': 24254, 'total_buses': 36418, 'private_trucks': 4583971, 'public_trucks': 81959, 'total_trucks': 4665930, 'private_motorcycles': 203064, 'public_motorcycles': 858, 'total_motorcycles': 203922, 'all_private': 8280920, 'all_public': 161405, 'total': 8442325, 'state_abbr': 'GA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad7')}, {'state': 'Hawaii', 'private_cars': 504605, 'public_cars': 7781, 'total_cars': 512386, 'private_buses': 1745, 'public_buses': 1288, 'total_buses': 3033, 'private_trucks': 693360, 'public_trucks': 15186, 'total_trucks': 708546, 'private_motorcycles': 35203, 'public_motorcycles': 373, 'total_motorcycles': 35576, 'all_private': 1234913, 'all_public': 24628, 'total': 1259541, 'state_abbr': 'HI', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad8')}, {'state': 'Idaho', 'private_cars': 547567, 'public_cars': 2439, 'total_cars': 550006, 'private_buses': 3243, 'public_buses': 627, 'total_buses': 3870, 'private_trucks': 1208288, 'public_trucks': 10442, 'total_trucks': 1218730, 'private_motorcycles': 63266, 'public_motorcycles': 31, 'total_motorcycles': 63297, 'all_private': 1822364, 'all_public': 13539, 'total': 1835903, 'state_abbr': 'ID', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fad9')}, {'state': 'Illinois', 'private_cars': 4617096, 'public_cars': 38748, 'total_cars': 4655844, 'private_buses': 34177, 'public_buses': 182, 'total_buses': 34359, 'private_trucks': 5806097, 'public_trucks': 60517, 'total_trucks': 5866614, 'private_motorcycles': 333943, 'public_motorcycles': 0, 'total_motorcycles': 333943, 'all_private': 10791313, 'all_public': 99447, 'total': 10890760, 'state_abbr': 'IL', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fada')}, {'state': 'Indiana', 'private_cars': 2258547, 'public_cars': 2893, 'total_cars': 2261440, 'private_buses': 7227, 'public_buses': 13498, 'total_buses': 20725, 'private_trucks': 3627258, 'public_trucks': 10032, 'total_trucks': 3637290, 'private_motorcycles': 250579, 'public_motorcycles': 0, 'total_motorcycles': 250579, 'all_private': 6143611, 'all_public': 26423, 'total': 6170034, 'state_abbr': 'IN', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fadb')}, {'state': 'Iowa', 'private_cars': 1257304, 'public_cars': 11692, 'total_cars': 1268996, 'private_buses': 3945, 'public_buses': 5339, 'total_buses': 9284, 'private_trucks': 2253531, 'public_trucks': 23663, 'total_trucks': 2277194, 'private_motorcycles': 194273, 'public_motorcycles': 330, 'total_motorcycles': 194603, 'all_private': 3709053, 'all_public': 41024, 'total': 3750077, 'state_abbr': 'IA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fadc')}, {'state': 'Kansas', 'private_cars': 983245, 'public_cars': 4014, 'total_cars': 987259, 'private_buses': 3961, 'public_buses': 2267, 'total_buses': 6228, 'private_trucks': 1618733, 'public_trucks': 9761, 'total_trucks': 1628494, 'private_motorcycles': 95892, 'public_motorcycles': 0, 'total_motorcycles': 95892, 'all_private': 2701831, 'all_public': 16042, 'total': 2717873, 'state_abbr': 'KS', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fadd')}, {'state': 'Kentucky', 'private_cars': 1659583, 'public_cars': 31502, 'total_cars': 1691085, 'private_buses': 1406, 'public_buses': 9353, 'total_buses': 10759, 'private_trucks': 2439925, 'public_trucks': 50273, 'total_trucks': 2490198, 'private_motorcycles': 101085, 'public_motorcycles': 78, 'total_motorcycles': 101163, 'all_private': 4201999, 'all_public': 91206, 'total': 4293205, 'state_abbr': 'KY', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fade')}, {'state': 'Louisiana', 'private_cars': 1360611, 'public_cars': 28825, 'total_cars': 1389436, 'private_buses': 22183, 'public_buses': 6977, 'total_buses': 29160, 'private_trucks': 2320545, 'public_trucks': 54007, 'total_trucks': 2374552, 'private_motorcycles': 113664, 'public_motorcycles': 0, 'total_motorcycles': 113664, 'all_private': 3817003, 'all_public': 89809, 'total': 3906812, 'state_abbr': 'LA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fadf')}, {'state': 'Maine', 'private_cars': 383228, 'public_cars': 4005, 'total_cars': 387233, 'private_buses': 1313, 'public_buses': 3026, 'total_buses': 4339, 'private_trucks': 643010, 'public_trucks': 8339, 'total_trucks': 651349, 'private_motorcycles': 51466, 'public_motorcycles': 1, 'total_motorcycles': 51467, 'all_private': 1079017, 'all_public': 15371, 'total': 1094388, 'state_abbr': 'ME', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae0')}, {'state': 'Maryland', 'private_cars': 1977742, 'public_cars': 29162, 'total_cars': 2006904, 'private_buses': 15233, 'public_buses': 7739, 'total_buses': 22972, 'private_trucks': 2167715, 'public_trucks': 41730, 'total_trucks': 2209445, 'private_motorcycles': 118201, 'public_motorcycles': 76, 'total_motorcycles': 118277, 'all_private': 4278891, 'all_public': 78707, 'total': 4357598, 'state_abbr': 'MD', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae1')}, {'state': 'Massachusetts', 'private_cars': 2204455, 'public_cars': 4013, 'total_cars': 2208468, 'private_buses': 13255, 'public_buses': 243, 'total_buses': 13498, 'private_trucks': 2662640, 'public_trucks': 11684, 'total_trucks': 2674324, 'private_motorcycles': 168931, 'public_motorcycles': 0, 'total_motorcycles': 168931, 'all_private': 5049281, 'all_public': 15940, 'total': 5065221, 'state_abbr': 'MA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae2')}, {'state': 'Michigan', 'private_cars': 3233241, 'public_cars': 24232, 'total_cars': 3257473, 'private_buses': 3397, 'public_buses': 5340, 'total_buses': 8737, 'private_trucks': 4947020, 'public_trucks': 46380, 'total_trucks': 4993400, 'private_motorcycles': 258487, 'public_motorcycles': 0, 'total_motorcycles': 258487, 'all_private': 8442145, 'all_public': 75952, 'total': 8518097, 'state_abbr': 'MI', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae3')}, {'state': 'Minnesota', 'private_cars': 2129307, 'public_cars': 16880, 'total_cars': 2146187, 'private_buses': 14338, 'public_buses': 5642, 'total_buses': 19980, 'private_trucks': 3243782, 'public_trucks': 31148, 'total_trucks': 3274930, 'private_motorcycles': 241556, 'public_motorcycles': 0, 'total_motorcycles': 241556, 'all_private': 5628983, 'all_public': 53670, 'total': 5682653, 'state_abbr': 'MN', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae4')}, {'state': 'Mississippi', 'private_cars': 820128, 'public_cars': 2736, 'total_cars': 822864, 'private_buses': 2023, 'public_buses': 5995, 'total_buses': 8018, 'private_trucks': 1190809, 'public_trucks': 7661, 'total_trucks': 1198470, 'private_motorcycles': 28124, 'public_motorcycles': 0, 'total_motorcycles': 28124, 'all_private': 2041084, 'all_public': 16392, 'total': 2057476, 'state_abbr': 'MS', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae5')}, {'state': 'Missouri', 'private_cars': 2122581, 'public_cars': 18469, 'total_cars': 2141050, 'private_buses': 27057, 'public_buses': 123, 'total_buses': 27180, 'private_trucks': 3227854, 'public_trucks': 34358, 'total_trucks': 3262212, 'private_motorcycles': 138294, 'public_motorcycles': 0, 'total_motorcycles': 138294, 'all_private': 5515786, 'all_public': 52950, 'total': 5568736, 'state_abbr': 'MO', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae6')}, {'state': 'Montana', 'private_cars': 440809, 'public_cars': 583, 'total_cars': 441392, 'private_buses': 4538, 'public_buses': 164, 'total_buses': 4702, 'private_trucks': 1104946, 'public_trucks': 6223, 'total_trucks': 1111169, 'private_motorcycles': 306651, 'public_motorcycles': 4, 'total_motorcycles': 306655, 'all_private': 1856944, 'all_public': 6974, 'total': 1863918, 'state_abbr': 'MT', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae7')}, {'state': 'Nebraska', 'private_cars': 662491, 'public_cars': 14549, 'total_cars': 677040, 'private_buses': 13526, 'public_buses': 38, 'total_buses': 13564, 'private_trucks': 1190469, 'public_trucks': 28296, 'total_trucks': 1218765, 'private_motorcycles': 55716, 'public_motorcycles': 20, 'total_motorcycles': 55736, 'all_private': 1922202, 'all_public': 42903, 'total': 1965105, 'state_abbr': 'NE', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae8')}, {'state': 'Nevada', 'private_cars': 1039514, 'public_cars': 7994, 'total_cars': 1047508, 'private_buses': 504, 'public_buses': 2694, 'total_buses': 3198, 'private_trucks': 1313087, 'public_trucks': 15617, 'total_trucks': 1328704, 'private_motorcycles': 76027, 'public_motorcycles': 5, 'total_motorcycles': 76032, 'all_private': 2429132, 'all_public': 26310, 'total': 2455442, 'state_abbr': 'NV', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34fae9')}, {'state': 'New Hampshire', 'private_cars': 502617, 'public_cars': 2764, 'total_cars': 505381, 'private_buses': 566, 'public_buses': 2305, 'total_buses': 2871, 'private_trucks': 726620, 'public_trucks': 5447, 'total_trucks': 732067, 'private_motorcycles': 78702, 'public_motorcycles': 96, 'total_motorcycles': 78798, 'all_private': 1308505, 'all_public': 10612, 'total': 1319117, 'state_abbr': 'NH', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faea')}, {'state': 'New Jersey', 'private_cars': 2774916, 'public_cars': 23783, 'total_cars': 2798699, 'private_buses': 22867, 'public_buses': 2230, 'total_buses': 25097, 'private_trucks': 3045425, 'public_trucks': 35511, 'total_trucks': 3080936, 'private_motorcycles': 152979, 'public_motorcycles': 0, 'total_motorcycles': 152979, 'all_private': 5996187, 'all_public': 61524, 'total': 6057711, 'state_abbr': 'NJ', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faeb')}, {'state': 'New Mexico', 'private_cars': 601647, 'public_cars': 7847, 'total_cars': 609494, 'private_buses': 6071, 'public_buses': 207, 'total_buses': 6278, 'private_trucks': 1043650, 'public_trucks': 22862, 'total_trucks': 1066512, 'private_motorcycles': 57718, 'public_motorcycles': 0, 'total_motorcycles': 57718, 'all_private': 1709086, 'all_public': 30916, 'total': 1740002, 'state_abbr': 'NM', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faec')}, {'state': 'New York', 'private_cars': 4541749, 'public_cars': 21286, 'total_cars': 4563035, 'private_buses': 74639, 'public_buses': 5807, 'total_buses': 80446, 'private_trucks': 5780052, 'public_trucks': 41744, 'total_trucks': 5821796, 'private_motorcycles': 392176, 'public_motorcycles': 2, 'total_motorcycles': 392178, 'all_private': 10788616, 'all_public': 68839, 'total': 10857455, 'state_abbr': 'NY', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faed')}, {'state': 'North Carolina', 'private_cars': 3271128, 'public_cars': 46790, 'total_cars': 3317918, 'private_buses': 11653, 'public_buses': 20840, 'total_buses': 32493, 'private_trucks': 4458666, 'public_trucks': 72797, 'total_trucks': 4531463, 'private_motorcycles': 188580, 'public_motorcycles': 263, 'total_motorcycles': 188843, 'all_private': 7930027, 'all_public': 140690, 'total': 8070717, 'state_abbr': 'NC', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faee')}, {'state': 'North Dakota', 'private_cars': 272290, 'public_cars': 4255, 'total_cars': 276545, 'private_buses': 1457, 'public_buses': 1874, 'total_buses': 3331, 'private_trucks': 711318, 'public_trucks': 13623, 'total_trucks': 724941, 'private_motorcycles': 51927, 'public_motorcycles': 14, 'total_motorcycles': 51941, 'all_private': 1036992, 'all_public': 19766, 'total': 1056758, 'state_abbr': 'ND', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faef')}, {'state': 'Ohio', 'private_cars': 4561052, 'public_cars': 44407, 'total_cars': 4605459, 'private_buses': 34699, 'public_buses': 6556, 'total_buses': 41255, 'private_trucks': 5686290, 'public_trucks': 66056, 'total_trucks': 5752346, 'private_motorcycles': 410165, 'public_motorcycles': 22, 'total_motorcycles': 410187, 'all_private': 10692206, 'all_public': 117041, 'total': 10809247, 'state_abbr': 'OH', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf0')}, {'state': 'Oklahoma', 'private_cars': 1330082, 'public_cars': 7542, 'total_cars': 1337624, 'private_buses': 1870, 'public_buses': 1285, 'total_buses': 3155, 'private_trucks': 2249920, 'public_trucks': 17289, 'total_trucks': 2267209, 'private_motorcycles': 136189, 'public_motorcycles': 1, 'total_motorcycles': 136190, 'all_private': 3718061, 'all_public': 26117, 'total': 3744178, 'state_abbr': 'OK', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf1')}, {'state': 'Oregon', 'private_cars': 1517573, 'public_cars': 24888, 'total_cars': 1542461, 'private_buses': 8541, 'public_buses': 9150, 'total_buses': 17691, 'private_trucks': 2354242, 'public_trucks': 46319, 'total_trucks': 2400561, 'private_motorcycles': 141987, 'public_motorcycles': 751, 'total_motorcycles': 142738, 'all_private': 4022343, 'all_public': 81108, 'total': 4103451, 'state_abbr': 'OR', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf2')}, {'state': 'Pennsylvania', 'private_cars': 4415164, 'public_cars': 48103, 'total_cars': 4463267, 'private_buses': 53192, 'public_buses': 2743, 'total_buses': 55935, 'private_trucks': 5719230, 'public_trucks': 73616, 'total_trucks': 5792846, 'private_motorcycles': 376390, 'public_motorcycles': 768, 'total_motorcycles': 377158, 'all_private': 10563976, 'all_public': 125230, 'total': 10689206, 'state_abbr': 'PA', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf3')}, {'state': 'Rhode Island', 'private_cars': 413227, 'public_cars': 7086, 'total_cars': 420313, 'private_buses': 1872, 'public_buses': 401, 'total_buses': 2273, 'private_trucks': 410744, 'public_trucks': 8570, 'total_trucks': 419314, 'private_motorcycles': 30814, 'public_motorcycles': 100, 'total_motorcycles': 30914, 'all_private': 856657, 'all_public': 16157, 'total': 872814, 'state_abbr': 'RI', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf4')}, {'state': 'South Carolina', 'private_cars': 1725328, 'public_cars': 83073, 'total_cars': 1808401, 'private_buses': 5476, 'public_buses': 12252, 'total_buses': 17728, 'private_trucks': 2342149, 'public_trucks': 117690, 'total_trucks': 2459839, 'private_motorcycles': 117660, 'public_motorcycles': 472, 'total_motorcycles': 118132, 'all_private': 4190613, 'all_public': 213487, 'total': 4404100, 'state_abbr': 'SC', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf5')}, {'state': 'South Dakota', 'private_cars': 347216, 'public_cars': 5964, 'total_cars': 353180, 'private_buses': 0, 'public_buses': 2614, 'total_buses': 2614, 'private_trucks': 769748, 'public_trucks': 15353, 'total_trucks': 785101, 'private_motorcycles': 116807, 'public_motorcycles': 654, 'total_motorcycles': 117461, 'all_private': 1233771, 'all_public': 24585, 'total': 1258356, 'state_abbr': 'SD', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf6')}, {'state': 'Tennessee', 'private_cars': 2274107, 'public_cars': 50897, 'total_cars': 2325004, 'private_buses': 2918, 'public_buses': 26240, 'total_buses': 29158, 'private_trucks': 3201416, 'public_trucks': 78943, 'total_trucks': 3280359, 'private_motorcycles': 163619, 'public_motorcycles': 2349, 'total_motorcycles': 165968, 'all_private': 5642060, 'all_public': 158429, 'total': 5800489, 'state_abbr': 'TN', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf7')}, {'state': 'Texas', 'private_cars': 8084454, 'public_cars': 92425, 'total_cars': 8176879, 'private_buses': 18425, 'public_buses': 48718, 'total_buses': 67143, 'private_trucks': 13341345, 'public_trucks': 180708, 'total_trucks': 13522053, 'private_motorcycles': 363764, 'public_motorcycles': 926, 'total_motorcycles': 364690, 'all_private': 21807988, 'all_public': 322777, 'total': 22130765, 'state_abbr': 'TX', 'year': '2017', '_id': ObjectId('5cafd42378a01b3a3c34faf8')}, {'state': 'Utah', 'private_cars':

In [20]:
file = "state_tier1_caps.csv"

#Read csv into Pandas
df = pd.read_csv(file)
df.head()

,Emissions are in 1000 tons,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,STATE_FIPS,STATE_ABBR,tier1_code,tier1_description,pollutant_code,emissions90,emissions96,emissions97,emissions98,emissions99,...,emissions09,emissions10,emissions11,emissions12,emissions13,emissions14,emissions_fixed,emissions15,emissions16,emissions17
1,01,AL,01,FUEL COMB. ELEC. UTIL.,CO,6.86859,8.06884,8.04705,8.12158,11.51526,...,10.9668444,10.4941125,9.9576446,9.6423108,9.326977,9.0116432,9.0116432,9.0116432,9.0116432,9.0116432
2,01,AL,01,FUEL COMB. ELEC. UTIL.,NH3,NaN,0.01516,0.01605,0.01597,0.01651,...,0.522571961,0.505945589,0.489319218,0.488462596,0.487605975,0.486749353,0.486749353,0.486749353,0.486749353,0.486749353
3,01,AL,01,FUEL COMB. ELEC. UTIL.,NOX,187.79386,219.009,209.98918,198.66722,186.3871,...,96.00923043,78.87946547,61.6871485,57.76831163,53.84947477,49.9306379,49.9306379,44.893997,27.631909,21.307058
4,01,AL,01,FUEL COMB. ELEC. UTIL.,PM10,8.85994,9.28102,8.83472,8.37946,29.21702,...,5.876249051,6.615406896,7.323321741,6.469981304,5.616640867,4.763300429,4.763300429,4.763300429,4.763300429,4.763300429

In [21]:
df.drop(df[df['Unnamed: 4'] != 'CO'].index,inplace=True)
df.head()

,Emissions are in 1000 tons,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
1,01,AL,01,FUEL COMB. ELEC. UTIL.,CO,6.86859,8.06884,8.04705,8.12158,11.51526,...,10.9668444,10.4941125,9.9576446,9.6423108,9.326977,9.0116432,9.0116432,9.0116432,9.0116432,9.0116432
8,01,AL,02,FUEL COMB. INDUSTRIAL,CO,25.73799,49.77487,48.15407,48.41578,43.88043,...,22.61858405,22.84104926,71.86470057,66.7471092,61.62951784,56.51192647,56.51192647,56.51192647,56.51192647,56.51192647
15,01,AL,03,FUEL COMB. OTHER,CO,89.93378,34.23424,34.29082,34.15163,65.515923,...,11.54395555,11.75324656,12.10373583,14.99790364,17.89207145,20.78623926,20.78623926,20.78623926,20.78623926,20.78623926
22,01,AL,04,CHEMICAL & ALLIED PRODUCT MFG,CO,54.70092,44.2331,45.59779,46.96713,7.85382,...,1.736527033,2.429740967,3.122954901,3.133777588,3.144600276,3.155422963,3.155422963,3.155422963,3.155422963,3.155422963
29,01,AL,05,METALS PROCESSING,CO,6.61641,36.1217,37.64911,36.8687,31.76794,...,17.58291247,14.28719843,10.9914844,11.17310068,11.35471695,11.53633323,11.53633323,11.53633323,11.53633323,11.53633323

In [22]:
# Rename columns
#df.rename(columns={'Leader': 'Commander'}, inplace=True)
df.rename(columns={'Unnamed: 1': 'State_Abbreviation', "Unnamed: 4":"Poluttant_Code", "Unnamed: 23":"2012_Emissions",
                  "Unnamed: 24":"2013_Emissions", "Unnamed: 25":"2014_Emissions", "Unnamed: 26":"2015_Emissions",
                  "Unnamed: 27":"2016_Emissions", "Unnamed: 28":"2017_Emissions"}, inplace=True)
          
df.head()

,Emissions are in 1000 tons,State_Abbreviation,Unnamed: 2,Unnamed: 3,Poluttant_Code,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,2012_Emissions,2013_Emissions,2014_Emissions,2015_Emissions,2016_Emissions,2017_Emissions
1,01,AL,01,FUEL COMB. ELEC. UTIL.,CO,6.86859,8.06884,8.04705,8.12158,11.51526,...,10.9668444,10.4941125,9.9576446,9.6423108,9.326977,9.0116432,9.0116432,9.0116432,9.0116432,9.0116432
8,01,AL,02,FUEL COMB. INDUSTRIAL,CO,25.73799,49.77487,48.15407,48.41578,43.88043,...,22.61858405,22.84104926,71.86470057,66.7471092,61.62951784,56.51192647,56.51192647,56.51192647,56.51192647,56.51192647
15,01,AL,03,FUEL COMB. OTHER,CO,89.93378,34.23424,34.29082,34.15163,65.515923,...,11.54395555,11.75324656,12.10373583,14.99790364,17.89207145,20.78623926,20.78623926,20.78623926,20.78623926,20.78623926
22,01,AL,04,CHEMICAL & ALLIED PRODUCT MFG,CO,54.70092,44.2331,45.59779,46.96713,7.85382,...,1.736527033,2.429740967,3.122954901,3.133777588,3.144600276,3.155422963,3.155422963,3.155422963,3.155422963,3.155422963
29,01,AL,05,METALS PROCESSING,CO,6.61641,36.1217,37.64911,36.8687,31.76794,...,17.58291247,14.28719843,10.9914844,11.17310068,11.35471695,11.53633323,11.53633323,11.53633323,11.53633323,11.53633323

In [23]:
df.drop(["Emissions are in 1000 tons", "Unnamed: 2", "Unnamed: 3", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10", "Unnamed: 11", "Unnamed: 12",
        "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17", "Unnamed: 18", "Unnamed: 19", "Unnamed: 20",
        "Unnamed: 21", "Unnamed: 22",], axis=1, inplace=True)

df.head()

,State_Abbreviation,Poluttant_Code,2012_Emissions,2013_Emissions,2014_Emissions,2015_Emissions,2016_Emissions,2017_Emissions
1,AL,CO,9.326977,9.0116432,9.0116432,9.0116432,9.0116432,9.0116432
8,AL,CO,61.62951784,56.51192647,56.51192647,56.51192647,56.51192647,56.51192647
15,AL,CO,17.89207145,20.78623926,20.78623926,20.78623926,20.78623926,20.78623926
22,AL,CO,3.144600276,3.155422963,3.155422963,3.155422963,3.155422963,3.155422963
29,AL,CO,11.35471695,11.53633323,11.53633323,11.53633323,11.53633323,11.53633323

In [24]:
df.dtypes

State_Abbreviation    object
Poluttant_Code        object
2012_Emissions        object
2013_Emissions        object
2014_Emissions        object
2015_Emissions        object
2016_Emissions        object
2017_Emissions        object
dtype: object

In [25]:
# df[["a", "b"]] = df[["a", "b"]].apply(pd.to_numeric)

df[["2012_Emissions", "2013_Emissions", "2014_Emissions", 
    "2015_Emissions", "2016_Emissions", "2017_Emissions"]] = df[["2012_Emissions", "2013_Emissions", "2014_Emissions", 
                                                                "2015_Emissions", "2016_Emissions", "2017_Emissions"]].apply(pd.to_numeric)

df.dtypes

State_Abbreviation     object
Poluttant_Code         object
2012_Emissions        float64
2013_Emissions        float64
2014_Emissions        float64
2015_Emissions        float64
2016_Emissions        float64
2017_Emissions        float64
dtype: object

In [26]:
df.head()

,State_Abbreviation,Poluttant_Code,2012_Emissions,2013_Emissions,2014_Emissions,2015_Emissions,2016_Emissions,2017_Emissions
1,AL,CO,9.326977,9.011643,9.011643,9.011643,9.011643,9.011643
8,AL,CO,61.629518,56.511926,56.511926,56.511926,56.511926,56.511926
15,AL,CO,17.892071,20.786239,20.786239,20.786239,20.786239,20.786239
22,AL,CO,3.144600,3.155423,3.155423,3.155423,3.155423,3.155423
29,AL,CO,11.354717,11.536333,11.536333,11.536333,11.536333,11.536333

In [27]:
# Replacing NaN values with 0
df.fillna(value=0.0,inplace=True)

In [28]:
grouped = df.groupby(["State_Abbreviation", "Poluttant_Code"])
df_grouped = pd.DataFrame({"2012 Emissions Total":grouped["2012_Emissions"].sum(),
                         "2013 Emissions Total":grouped["2013_Emissions"].sum(),
                         "2014 Emissions Total":grouped["2014_Emissions"].sum(),
                         "2015 Emissions Total":grouped["2015_Emissions"].sum(),
                         "2016 Emissions Total":grouped["2016_Emissions"].sum(),
                         "2017 Emissions Total":grouped["2017_Emissions"].sum()})


df_grouped.head()

,,2012 Emissions Total,2013 Emissions Total,2014 Emissions Total,2015 Emissions Total,2016 Emissions Total,2017 Emissions Total
State_Abbreviation,Poluttant_Code,,,,,,
AK,CO,2346.916178,2300.045425,195.699049,2299.679313,2299.313202,2298.947090
AL,CO,1893.958290,1929.506064,1175.462871,1895.847216,1807.671136,1746.753673
AR,CO,1239.014331,1156.753717,581.843928,1146.147183,1101.524547,1073.909962
AZ,CO,1632.243281,1237.286833,930.156797,1231.447180,1157.617056,1117.782167
CA,CO,4960.917428,5604.151765,2047.876790,5522.191042,5440.301417,5358.376243

In [29]:
df_grouped = df_grouped.reset_index(level="State_Abbreviation")
df_grouped = df_grouped.reset_index(level="Poluttant_Code")

df_grouped.head()

,Poluttant_Code,State_Abbreviation,2012 Emissions Total,2013 Emissions Total,2014 Emissions Total,2015 Emissions Total,2016 Emissions Total,2017 Emissions Total
0,CO,AK,2346.916178,2300.045425,195.699049,2299.679313,2299.313202,2298.947090
1,CO,AL,1893.958290,1929.506064,1175.462871,1895.847216,1807.671136,1746.753673
2,CO,AR,1239.014331,1156.753717,581.843928,1146.147183,1101.524547,1073.909962
3,CO,AZ,1632.243281,1237.286833,930.156797,1231.447180,1157.617056,1117.782167
4,CO,CA,4960.917428,5604.151765,2047.876790,5522.191042,5440.301417,5358.376243

In [30]:
pol_db_input = []
for index, row in df_grouped.iterrows():
        state_record = {}
        for i in df_grouped.columns:
            state_record[i] = row[i]
        pol_db_input.append(state_record)
    
print (pol_db_input)

[{'Poluttant_Code': 'CO', 'State_Abbreviation': 'AK', '2012 Emissions Total': 2346.916178412, '2013 Emissions Total': 2300.0454249700006, '2014 Emissions Total': 195.699049425, '2015 Emissions Total': 2299.6793134100003, '2016 Emissions Total': 2299.3132018500005, '2017 Emissions Total': 2298.9470902800003}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'AL', '2012 Emissions Total': 1893.958290067, '2013 Emissions Total': 1929.506063627, '2014 Emissions Total': 1175.4628710729999, '2015 Emissions Total': 1895.847216227, '2016 Emissions Total': 1807.671136427, '2017 Emissions Total': 1746.753672927}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'AR', '2012 Emissions Total': 1239.014331205, '2013 Emissions Total': 1156.7537166020002, '2014 Emissions Total': 581.843927572, '2015 Emissions Total': 1146.1471826020002, '2016 Emissions Total': 1101.524546602, '2017 Emissions Total': 1073.909961602}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'AZ', '2012 Emissions Total': 1632.2432806759998, '2013 Emissions Total': 1237.2868334009997, '2014 Emissions Total': 930.1567972169998, '2015 Emissions Total': 1231.447179801, '2016 Emissions Total': 1157.6170562009997, '2017 Emissions Total': 1117.782167401}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'CA', '2012 Emissions Total': 4960.9174277639995, '2013 Emissions Total': 5604.151765116, '2014 Emissions Total': 2047.8767898560002, '2015 Emissions Total': 5522.191042116, '2016 Emissions Total': 5440.301417216, '2017 Emissions Total': 5358.376243116}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'CO', '2012 Emissions Total': 1084.69741932, '2013 Emissions Total': 919.8990675549999, '2014 Emissions Total': 846.164902928, '2015 Emissions Total': 889.632987955, '2016 Emissions Total': 825.065967655, '2017 Emissions Total': 777.6494176549999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'CT', '2012 Emissions Total': 410.4986269070001, '2013 Emissions Total': 400.1494803612, '2014 Emissions Total': 399.427587755, '2015 Emissions Total': 387.2720417612, '2016 Emissions Total': 359.9642919612, '2017 Emissions Total': 339.8716977612}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'DC', '2012 Emissions Total': 45.381695633300005, '2013 Emissions Total': 47.29803849489999, '2014 Emissions Total': 47.29802804399999, '2015 Emissions Total': 45.621968564899994, '2016 Emissions Total': 40.411948684900004, '2017 Emissions Total': 36.9689037849}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'DE', '2012 Emissions Total': 130.44782182533, '2013 Emissions Total': 133.38957094900002, '2014 Emissions Total': 131.606573902, '2015 Emissions Total': 128.86104576900001, '2016 Emissions Total': 123.11702454899999, '2017 Emissions Total': 117.980751359}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'FL', '2012 Emissions Total': 4162.360126967, '2013 Emissions Total': 4206.079210568, '2014 Emissions Total': 3004.593499088, '2015 Emissions Total': 4180.216146568, '2016 Emissions Total': 4030.5050885680002, '2017 Emissions Total': 3942.718028568}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'GA', '2012 Emissions Total': 2401.854328247, '2013 Emissions Total': 2192.241363958, '2014 Emissions Total': 1684.94919781, '2015 Emissions Total': 2247.922615558, '2016 Emissions Total': 2144.867745058, '2017 Emissions Total': 2121.180935658}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'HI', '2012 Emissions Total': 254.40462345400002, '2013 Emissions Total': 283.937791536, '2014 Emissions Total': 169.733356711, '2015 Emissions Total': 283.330677696, '2016 Emissions Total': 282.723563856, '2017 Emissions Total': 282.116450026}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'IA', '2012 Emissions Total': 772.0093217040002, '2013 Emissions Total': 772.011519352, '2014 Emissions Total': 635.733290781, '2015 Emissions Total': 760.3768963519999, '2016 Emissions Total': 710.216725752, '2017 Emissions Total': 679.3193290520001}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'ID', '2012 Emissions Total': 1028.4708572729999, '2013 Emissions Total': 987.3860571729999, '2014 Emissions Total': 337.968958303, '2015 Emissions Total': 974.8391674229999, '2016 Emissions Total': 940.8374048629998, '2017 Emissions Total': 917.563078713}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'IL', '2012 Emissions Total': 1709.7485997289996, '2013 Emissions Total': 1784.6809031460002, '2014 Emissions Total': 1672.7825642940002, '2015 Emissions Total': 1694.510029346, '2016 Emissions Total': 1616.576578446, '2017 Emissions Total': 1532.524416146}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'IN', '2012 Emissions Total': 1546.3834002659999, '2013 Emissions Total': 1511.0744736549998, '2014 Emissions Total': 1449.9883162429996, '2015 Emissions Total': 1445.483887755, '2016 Emissions Total': 1398.549552455, '2017 Emissions Total': 1342.287091855}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'KS', '2012 Emissions Total': 1245.656523769, '2013 Emissions Total': 1012.6436626309999, '2014 Emissions Total': 660.6867671709999, '2015 Emissions Total': 995.8109938309999, '2016 Emissions Total': 947.3529480309999, '2017 Emissions Total': 914.7075906309999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'KY', '2012 Emissions Total': 1162.3811915109998, '2013 Emissions Total': 1199.0423328989998, '2014 Emissions Total': 850.3238100629999, '2015 Emissions Total': 1167.3427330989998, '2016 Emissions Total': 1114.428723499, '2017 Emissions Total': 1072.1219187989998}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'LA', '2012 Emissions Total': 2072.3986885589998, '2013 Emissions Total': 1942.231889942, '2014 Emissions Total': 882.005457612, '2015 Emissions Total': 1916.0855665419997, '2016 Emissions Total': 1878.242178842, '2017 Emissions Total': 1846.247323242}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MA', '2012 Emissions Total': 703.184906089, '2013 Emissions Total': 696.3777327390001, '2014 Emissions Total': 692.452565043, '2015 Emissions Total': 682.8997431390001, '2016 Emissions Total': 656.566239139, '2017 Emissions Total': 636.6604922390001}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MD', '2012 Emissions Total': 733.074119774, '2013 Emissions Total': 723.3551525419999, '2014 Emissions Total': 688.090526495, '2015 Emissions Total': 721.3183588420001, '2016 Emissions Total': 680.844685242, '2017 Emissions Total': 659.589451642}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'ME', '2012 Emissions Total': 286.20597581399994, '2013 Emissions Total': 284.29755634, '2014 Emissions Total': 278.57497793100003, '2015 Emissions Total': 278.22530129, '2016 Emissions Total': 263.48933116, '2017 Emissions Total': 253.08521854999998}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MI', '2012 Emissions Total': 1862.5621730130001, '2013 Emissions Total': 1744.8564945320002, '2014 Emissions Total': 1713.846973535, '2015 Emissions Total': 1673.178192132, '2016 Emissions Total': 1593.3678110320002, '2017 Emissions Total': 1517.6234692320002}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MN', '2012 Emissions Total': 1761.7925700380001, '2013 Emissions Total': 1599.11911953, '2014 Emissions Total': 1338.117553373, '2015 Emissions Total': 1533.74200483, '2016 Emissions Total': 1473.4434460300001, '2017 Emissions Total': 1410.6056093299999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MO', '2012 Emissions Total': 1860.2260116879997, '2013 Emissions Total': 1941.764011274, '2014 Emissions Total': 1189.954490314, '2015 Emissions Total': 1899.0484175740003, '2016 Emissions Total': 1819.449744474, '2017 Emissions Total': 1758.292611074}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MS', '2012 Emissions Total': 972.892043949, '2013 Emissions Total': 934.25967054, '2014 Emissions Total': 632.6560035269999, '2015 Emissions Total': 914.4022977399999, '2016 Emissions Total': 865.38917684, '2017 Emissions Total': 830.95392994}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'MT', '2012 Emissions Total': 858.2925951279999, '2013 Emissions Total': 627.0490642770001, '2014 Emissions Total': 291.496230742, '2015 Emissions Total': 610.721951197, '2016 Emissions Total': 570.6053290069999, '2017 Emissions Total': 542.383461317}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NC', '2012 Emissions Total': 1721.8905416419998, '2013 Emissions Total': 1636.685322111, '2014 Emissions Total': 1470.50311949, '2015 Emissions Total': 1598.689073511, '2016 Emissions Total': 1519.763807911, '2017 Emissions Total': 1461.3030508109998}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'ND', '2012 Emissions Total': 400.853112271, '2013 Emissions Total': 357.02404254299995, '2014 Emissions Total': 227.04401185199998, '2015 Emissions Total': 342.280050113, '2016 Emissions Total': 322.782082833, '2017 Emissions Total': 305.66110296299996}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NE', '2012 Emissions Total': 483.014180486, '2013 Emissions Total': 463.576275056, '2014 Emissions Total': 377.086425009, '2015 Emissions Total': 451.868920556, '2016 Emissions Total': 420.41824575600003, '2017 Emissions Total': 398.839231156}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NH', '2012 Emissions Total': 232.721084123, '2013 Emissions Total': 226.73534040799998, '2014 Emissions Total': 226.039447189, '2015 Emissions Total': 220.741080078, '2016 Emissions Total': 210.40373779799998, '2017 Emissions Total': 202.237936488}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NJ', '2012 Emissions Total': 917.6131434149999, '2013 Emissions Total': 908.0504675829998, '2014 Emissions Total': 817.0376744089999, '2015 Emissions Total': 890.8038650829999, '2016 Emissions Total': 869.301550383, '2017 Emissions Total': 849.9270916829998}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NM', '2012 Emissions Total': 830.0409820607, '2013 Emissions Total': 513.487609809, '2014 Emissions Total': 408.055244081, '2015 Emissions Total': 517.350148179, '2016 Emissions Total': 482.483698659, '2017 Emissions Total': 466.98174302900003}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NV', '2012 Emissions Total': 510.865663052, '2013 Emissions Total': 491.905508359, '2014 Emissions Total': 382.469695527, '2015 Emissions Total': 483.427400559, '2016 Emissions Total': 462.678007759, '2017 Emissions Total': 448.064257459}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'NY', '2012 Emissions Total': 1897.9462125359998, '2013 Emissions Total': 1884.2480294959998, '2014 Emissions Total': 1870.273680955, '2015 Emissions Total': 1818.037989596, '2016 Emissions Total': 1687.1916161959998, '2017 Emissions Total': 1588.6634095959998}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'OH', '2012 Emissions Total': 2147.0509318659997, '2013 Emissions Total': 1882.226417614, '2014 Emissions Total': 1841.164510266, '2015 Emissions Total': 1816.5802890139998, '2016 Emissions Total': 1761.933451614, '2017 Emissions Total': 1701.786968714}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'OK', '2012 Emissions Total': 1522.373481421, '2013 Emissions Total': 1311.016985321, '2014 Emissions Total': 805.281182481, '2015 Emissions Total': 1283.375262021, '2016 Emissions Total': 1234.789430421, '2017 Emissions Total': 1196.675653021}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'OR', '2012 Emissions Total': 2289.48457451, '2013 Emissions Total': 2291.871519846, '2014 Emissions Total': 687.923198776, '2015 Emissions Total': 2272.0745648459997, '2016 Emissions Total': 2207.6869583459998, '2017 Emissions Total': 2165.5946775459997}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'PA', '2012 Emissions Total': 1777.919389564, '2013 Emissions Total': 1714.2864746639998, '2014 Emissions Total': 1675.5519214199999, '2015 Emissions Total': 1656.5907007639998, '2016 Emissions Total': 1561.1524523639998, '2017 Emissions Total': 1484.5854412639999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'RI', '2012 Emissions Total': 124.69282568999999, '2013 Emissions Total': 124.01890842939, '2014 Emissions Total': 123.842948014, '2015 Emissions Total': 120.72769199939, '2016 Emissions Total': 113.55977470939, '2017 Emissions Total': 108.33020783939}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'SC', '2012 Emissions Total': 1145.935674673, '2013 Emissions Total': 1168.36462463, '2014 Emissions Total': 910.15744923, '2015 Emissions Total': 1149.6375395300001, '2016 Emissions Total': 1118.41546683, '2017 Emissions Total': 1093.44088793}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'SD', '2012 Emissions Total': 486.52148608100003, '2013 Emissions Total': 375.72868671900005, '2014 Emissions Total': 192.62642170200002, '2015 Emissions Total': 367.129203349, '2016 Emissions Total': 348.439572789, '2017 Emissions Total': 334.79501585900005}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'TN', '2012 Emissions Total': 1330.6192773900002, '2013 Emissions Total': 1352.0340774129997, '2014 Emissions Total': 1166.631292783, '2015 Emissions Total': 1338.5301739129998, '2016 Emissions Total': 1253.543598113, '2017 Emissions Total': 1204.298358413}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'TX', '2012 Emissions Total': 4393.634939746999, '2013 Emissions Total': 3715.2225114599996, '2014 Emissions Total': 3098.4662767199998, '2015 Emissions Total': 3791.8572307600007, '2016 Emissions Total': 3615.5041220599996, '2017 Emissions Total': 3565.64492736}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'UT', '2012 Emissions Total': 513.986681745, '2013 Emissions Total': 497.66772453600004, '2014 Emissions Total': 423.20322366700003, '2015 Emissions Total': 490.163808336, '2016 Emissions Total': 467.56359593599996, '2017 Emissions Total': 452.51153173599994}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'VA', '2012 Emissions Total': 1361.885793945, '2013 Emissions Total': 1408.2905063039998, '2014 Emissions Total': 1217.1154314619998, '2015 Emissions Total': 1390.618812904, '2016 Emissions Total': 1317.1628712039997, '2017 Emissions Total': 1271.5990537039997}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'VT', '2012 Emissions Total': 145.12872711999998, '2013 Emissions Total': 143.52882423699998, '2014 Emissions Total': 142.16419904499998, '2015 Emissions Total': 140.918670397, '2016 Emissions Total': 134.889392837, '2017 Emissions Total': 130.569677147}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'WA', '2012 Emissions Total': 2329.547046878, '2013 Emissions Total': 2670.3325484380002, '2014 Emissions Total': 1234.701118768, '2015 Emissions Total': 2622.233131338, '2016 Emissions Total': 2513.073240738, '2017 Emissions Total': 2434.443586938}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'WI', '2012 Emissions Total': 1174.418319908, '2013 Emissions Total': 1121.268109545, '2014 Emissions Total': 1072.468339129, '2015 Emissions Total': 1080.322615545, '2016 Emissions Total': 1035.8954752450002, '2017 Emissions Total': 993.2091580449999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'WV', '2012 Emissions Total': 495.90176695599996, '2013 Emissions Total': 502.800156451, '2014 Emissions Total': 355.253825489, '2015 Emissions Total': 495.32386546099997, '2016 Emissions Total': 470.980109461, '2017 Emissions Total': 455.0700859609999}, {'Poluttant_Code': 'CO', 'State_Abbreviation': 'WY', '2012 Emissions Total': 569.365915847, '2013 Emissions Total': 292.861236326, '2014 Emissions Total': 210.39650829099998, '2015 Emissions Total': 285.036385686, '2016 Emissions Total': 264.441614376, '2017 Emissions Total': 250.231803396}]

In [31]:
db.pollution_records.insert_many(pol_db_input)